In [9]:
import numpy as np
lst=[10,20,30,40,50,60,70,80,90,15,25,35]
print("content of list :",lst)
print("Type of list :", type(lst))
print('-----------------------------')
a=np.array(lst)
print("Array is :", a)
print("Data Type is :", type(a))

content of list : [10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 35]
Type of list : <class 'list'>
-----------------------------
Array is : [10 20 30 40 50 60 70 80 90 15 25 35]
Data Type is : <class 'numpy.ndarray'>


In [15]:
import numpy as np
lst=[10,20,30,40,50,60,70,80,90,15,25,35]
print("content of list :",lst)
print("Type of list :", type(lst))
print('-----------------------------')
a=np.array(lst)
print("Array is :", a)
print("Data Type is :", type(a))
a.shape=(2,3,2)
print(a)
print("Dtype is :", a.dtype)
print("Size is :", a.size)
print("Dimension is :", a.ndim)
print("Shape is :", a.shape)


content of list : [10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 35]
Type of list : <class 'list'>
-----------------------------
Array is : [10 20 30 40 50 60 70 80 90 15 25 35]
Data Type is : <class 'numpy.ndarray'>
[[[10 20]
  [30 40]
  [50 60]]

 [[70 80]
  [90 15]
  [25 35]]]
Dtype is : int64
Size is : 12
Dimension is : 3
Shape is : (2, 3, 2)


In [19]:
lst=[[10,20,30],[40,50,60],[70,80,90]]
print(lst)
print(type(lst))
a=np.array(lst)
print(a)
print(type(a))
print("Dimension is :", a.ndim)
print("Shape is :", a.shape)
print("Size is :", a.size)
print("Data type is :", a.dtype)
print("item-size is :", a.itemsize)

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]
<class 'list'>
[[10 20 30]
 [40 50 60]
 [70 80 90]]
<class 'numpy.ndarray'>
Dimension is : 2
Shape is : (3, 3)
Size is : 9
Data type is : int64
item-size is : 8


In [24]:
tup=([10,20,30],[40,50,60],[70,80,90])
print(tup)
print(type(tup))
# converting tuple object into ndarray
a=np.array(tup)
print("Array =\n",a)
print("Type of Array =",type(a))
print("Dimension is =", a.ndim)
print("Shape is =", a.shape)
print("Size is =", a.size)
print("Data Type is =", a.dtype)

([10, 20, 30], [40, 50, 60], [70, 80, 90])
<class 'tuple'>
Array =
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Type of Array = <class 'numpy.ndarray'>
Dimension is = 2
Shape is = (3, 3)
Size is = 9
Data Type is = int64


In [28]:
num=10
print(num, type(num))
a=np.array(num)
print(a, type(a))
print("Dimension is ", a.ndim)
print("Shape is ", a.shape)
print("size is ", a.size)
print("data type is ", a.dtype)
print("item-size is ", a.itemsize)

10 <class 'int'>
10 <class 'numpy.ndarray'>
Dimension is  0
Shape is  ()
size is  1
data type is  int64
item-size is  8


In [34]:
# now converting the set object in ndarray
s1={10,20,30,40,50,60,70,80,90,100}
print(s1,type(s1))
a=np.array(s1)
print("content of array is :", a)
print("Type =", type(a))
print('-----------------------')
print("Dimension =", a.ndim)
print("Size is =", a.size)
print("Shape is =", a.shape)

{100, 70, 40, 10, 80, 50, 20, 90, 60, 30} <class 'set'>
content of array is : {100, 70, 40, 10, 80, 50, 20, 90, 60, 30}
Type = <class 'numpy.ndarray'>
-----------------------
Dimension = 0
Size is = 1
Shape is = ()


In [37]:
# Converting dictionary object into ndarray
d1={1:"Python",2:"C",3:"C++",4:"Java"}
print("dictionary =", d1)
print("Type =", type(d1))
print('-------------------------')
ad=np.array(d1)
print("Array is ", ad)
print("Type =>", type(ad))
print("Dimension =", ad.ndim)
print("size =", ad.size)
print("shape =", ad.shape)

dictionary = {1: 'Python', 2: 'C', 3: 'C++', 4: 'Java'}
Type = <class 'dict'>
-------------------------
Array is  {1: 'Python', 2: 'C', 3: 'C++', 4: 'Java'}
Type => <class 'numpy.ndarray'>
Dimension = 0
size = 1
shape = ()


In [44]:
s='Python'
lst=list(s)
a=np.array(lst)
a.shape=(3,2)
print(a,type(a))

[['P' 'y']
 ['t' 'h']
 ['o' 'n']] <class 'numpy.ndarray'>
