In [2]:
# Advanced Slicing Operations on 1-D 
import numpy as np
a=np.array(range(10,100,10))
print("content of a =", a)
print("Dimension of a =", a.ndim)

content of a = [10 20 30 40 50 60 70 80 90]
Dimension of a = 1


In [ ]:
#Get Random values like 10 60 80 of 1-D
#Step-1: Identify the Indices of 10 60 and 80----[0,5,7] OR [-9,-4,-2]
#Step-2: Pass Random Elements Indices to 1-darray object---ndarrayobj[ [Indices] ]

In [10]:
#Get Random values like 10 60 80 of 1-D
#Step-1
rind=[0,5,7]
#Step-2
a[rind]

array([10, 60, 80])

In [9]:
# with -ve index
ind=[-9,-4,-2]
a[ind]

array([10, 60, 80])

In [11]:
a[[0,5,7]]

array([10, 60, 80])

In [13]:
a[[-9,-4,-2]]

array([10, 60, 80])

In [14]:
print(a)

[10 20 30 40 50 60 70 80 90]


In [17]:
# get 20 80 20
a[[1,7,1]]

array([20, 80, 20])

In [18]:
a[[-8,-2,-8]]

array([20, 80, 20])

In [19]:
print(a)

[10 20 30 40 50 60 70 80 90]


In [20]:
# get 40 20 70 90
ind=[3,1,6,8]
a[ind]

array([40, 20, 70, 90])

In [21]:
ind=[-6,-8,-3,-1]
a[ind]

array([40, 20, 70, 90])

In [25]:
# Advanced Slicing Operations on 2-D 
a=np.array(range(10,100,10)).reshape(3,3)
print("content of a \n", a)
print("Dimension of a =", a.ndim)

content of a 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of a = 2


In [ ]:
#Step-1: Get Row Indices of Random Elements of 2-D
#Step-2: Get Col Indices of Random Elements of 2-D
#Step-3: Pass (row indices) and (col indices) to 2-Darray

In [29]:
# Get Principle Diagonal Elements----10 50 90
rind=[0,1,2]
cind=[0,1,2]
a[rind,cind]

array([10, 50, 90])

In [28]:
# OR
rind=[-3,-2,-1]
cind=[-3,-2,-1]
a[rind,cind]

array([10, 50, 90])

In [30]:
a[[0,1,2],[0,1,2]]

array([10, 50, 90])

In [35]:
# get in reverse order
a[rind,cind][::-1]

array([90, 50, 10])

In [36]:
a[[0,1,2],[0,1,2]][::-1]

array([90, 50, 10])

In [31]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [34]:
# get 50 and 90
a[[1,2],[1,2]] # pvm take as [(1,1),(2,2)]

array([50, 90])

In [33]:
a[[-2,-1],[-2,-1]]

array([50, 90])

In [37]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [38]:
# get 30 50 70
rind=[0,1,2]
cind=[2,1,0]
a[rind,cind]

array([30, 50, 70])

In [40]:
a[(-3,-2,-1),(-1,-2,-3)]

array([30, 50, 70])

In [41]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [43]:
# get 10 60 70
a[(0,1,2),(0,2,0)]

array([10, 60, 70])

In [44]:
a[[-3,-2,-1],[-3,-1,-3]]

array([10, 60, 70])

In [45]:
# get 10 40 60 90
a[(0,1,1,2),(0,0,2,2)]

array([10, 40, 60, 90])

In [ ]:
# Advanced Slicing Operations on 3-D 
# Step-1 : Get Matices Indices of Random Elements of 3-D
# Step-2: Get Row Indices of Random Elements of 3-D
# Step-3: Get Col Indices of Random Elements of 3-D
# Step-4: Pass (matrix Indices),(row indices) and (col indices) to 3-Darray

In [47]:
import numpy as np
a=np.arange(3*3*3).reshape(3,3,3)
print("content of a =\n", a)
print("Dimension of a=", a.ndim)

content of a =
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension of a= 3


In [48]:
# Get the Elements 4, 12 and 26 
# get matrix indexes
mind=[0,1,2]
rind=[1,1,2]
cind=[1,0,2]
a[mind,rind,cind]

array([ 4, 12, 26])

In [49]:
a[(0,1,2),(1,1,2),(1,0,2)]

array([ 4, 12, 26])

In [50]:
# with -ve index
a[[-3,-2,-1],[-2,-2,-1],[-2,-3,-1]]

array([ 4, 12, 26])

In [51]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [55]:
# Get 0 4 8  20 22 24
a[[0,0,0,2,2,2],[0,1,2,0,1,2],[0,1,2,2,1,0]]

array([ 0,  4,  8, 20, 22, 24])

In [56]:
a[(-3,-3,-3,-1,-1,-1),(-3,-2,-1,-3,-2,-1),(-3,-2,-1,-1,-2,-3)]

array([ 0,  4,  8, 20, 22, 24])

In [57]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [58]:
# 9 13 17
a[[1,1,1],[0,1,2],[0,1,2]]

array([ 9, 13, 17])

In [61]:
a[[2][0:1][0:3]]

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [62]:
a[[2][0:1][0:3]]

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [65]:
a[2:3,0:1,0:3]

array([[[18, 19, 20]]])

In [66]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [69]:
# get 0 4 8 11 13 15 18 22 26
mind=[0,0,0,1,1,1,2,2,2]
rind=[0,1,2,0,1,2,0,1,2]
cind=[0,1,2,2,1,0,0,1,2]
a[mind,rind,cind]

array([ 0,  4,  8, 11, 13, 15, 18, 22, 26])

In [70]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [71]:
# get 15 13 11 6 4 2 24 22 20
mind=[1,1,1,0,0,0,2,2,2]
rind=[2,1,0,2,1,0,2,1,0]
cind=[0,1,2,0,1,2,0,1,2]
a[mind,rind,cind]

array([15, 13, 11,  6,  4,  2, 24, 22, 20])