In [3]:
# Numpy -> append() on 1d array
import numpy as np
arr = np.arange(10,50,10)
print("Before append array is =", arr)

arr = np.append(arr,99)
print("After append array is =", arr)

Before append array is = [10 20 30 40]
After append array is = [10 20 30 40 99]


In [10]:
# multiple values
arr = np.arange(1,6)
print("Before append array is =", arr)

arr = np.append(arr, [10,20,30])
print("After append array is =", arr)

Before append array is = [1 2 3 4 5]
After append array is = [ 1  2  3  4  5 10 20 30]


In [13]:
# append() on 2d array
arr = np.arange(10,70,10).reshape(2,3)
print("Before append array is =\n", arr)

# appending row => axis=0
arr = np.append(arr, [[70,80,90]],axis=0)
print("After append array is =\n", arr)

Before append array is =
 [[10 20 30]
 [40 50 60]]
After append array is =
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [15]:
# inserting multiple rows
arr = np.arange(10,70,10).reshape(2,3)
print("Before append array is =\n", arr)

# appending row => axis=0
arr = np.append(arr,[[22,33,44],[55,66,77]],axis=0) # Row inserting
print("After append array is =\n", arr)

Before append array is =
 [[10 20 30]
 [40 50 60]]
After append array is =
 [[10 20 30]
 [40 50 60]
 [22 33 44]
 [55 66 77]]


In [16]:
# appending column
arr = np.arange(10,70,10).reshape(2,3)
print("Before append array is =\n", arr)

# appending column => axis=1
arr = np.append(arr,[[45],[55]],axis=1)  # column inserting
print("After append array is =\n", arr)

Before append array is =
 [[10 20 30]
 [40 50 60]]
After append array is =
 [[10 20 30 45]
 [40 50 60 55]]


In [23]:
# appending multiple column
arr = np.arange(10,70,10).reshape(2,3)
print("Before append array is =\n", arr)

# appending column => axis=1
arr = np.append(arr,[[88],[99]],axis=1)
arr = np.append(arr,[[55],[66]],axis=1)
print("After append array is =\n", arr)

Before append array is =
 [[10 20 30]
 [40 50 60]]
After append array is =
 [[10 20 30 88 55]
 [40 50 60 99 66]]


In [26]:
# numpy--inserting the value to 1D
import numpy as np
arr = np.arange(10,60,10)
print("Before insert array is =", arr)

# insert an element 35 at index 2
arr = np.insert(arr,2,35)
print("After inserting values is =", arr)

Before insert array is = [10 20 30 40 50]
After inserting values is = [10 20 35 30 40 50]


In [28]:
# insert an element 35,45,55 at index 2
import numpy as np
arr = np.arange(10,60,10)
print("Before insert array is =", arr)

arr = np.insert(arr,2,[35,45,55])
print("After inserting array is =", arr)

Before insert array is = [10 20 30 40 50]
After inserting array is = [10 20 35 45 55 30 40 50]


In [32]:
# numpy--inserting Multiple values to 1D at different Indices
import numpy as np
arr = np.arange(10,60,10)
print("Before inserting array is =", arr)

# insert an element 35 at index 2 and 49 in index 4
arr = np.insert(arr,[2,4],[35,49])
print("After inserting array is =", arr)

Before inserting array is = [10 20 30 40 50]
After inserting array is = [10 20 35 30 40 49 50]


In [35]:
arr = np.array([10,20,30,40,50,60])
print("Before Insert-Content",end=' ')
print(arr)

#insert an element 35,45,55 at index 2
arr = np.insert(arr,2,[35,45,55])
print("After Insert array is =", arr)

Before Insert-Content [10 20 30 40 50 60]
After Insert array is = [10 20 35 45 55 30 40 50 60]


In [44]:
# Numpy--insert() on 2D array
import numpy as np
arr = np.arange(10,70,10).reshape(2,3)
print("Before Insert-Content =\n", arr)
print('-'*40)

# inserting single Rows
arr = np.insert(arr,1,[[33,44,55]],axis=0)
print("After insert array is =\n", arr)

Before Insert-Content =
 [[10 20 30]
 [40 50 60]]
----------------------------------------
After insert array is =
 [[10 20 30]
 [33 44 55]
 [40 50 60]]


In [45]:
import numpy as np
arr = np.arange(10,70,10).reshape(2,3)
print("Before Insert-Content =\n", arr)
print('-'*40)

# inserting multiple rows
arr = np.insert(arr,[0,2],[[100,200,300],[400,500,600]],axis=0)
print("After insert array is =\n", arr)

Before Insert-Content =
 [[10 20 30]
 [40 50 60]]
----------------------------------------
After insert array is =
 [[100 200 300]
 [ 10  20  30]
 [ 40  50  60]
 [400 500 600]]


In [9]:
import numpy as np
arr = np.arange(10,100,10).reshape(3,3)
print("Before Insert-Content =\n", arr)
print('-'*40)

# insert single column
arr = np.insert(arr,1,[22,33,44],axis=1)   # axis=1 means column
print("After insert array is =\n", arr)
print('-'*40)

# insert single column
arr = np.insert(arr,2,[97,98,99],axis=1)   # axis=1 means column
print("After insert array is =\n", arr)

Before Insert-Content =
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
----------------------------------------
After insert array is =
 [[10 22 20 30]
 [40 33 50 60]
 [70 44 80 90]]
----------------------------------------
After insert array is =
 [[10 22 97 20 30]
 [40 33 98 50 60]
 [70 44 99 80 90]]


In [7]:
# Inserting Multiple Columns at multiple Column Indices
import numpy as np
arr = np.arange(10,100,10).reshape(3,3)
print("Content of array is =\n", arr)
print('--------------')
arr = np.insert(arr,[0,2],[[222,333],[222,333],[222,333]],axis=1)
print("After inserting array becomes =\n", arr)

Content of array is =
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
--------------
After inserting array becomes =
 [[222  10  20 333  30]
 [222  40  50 333  60]
 [222  70  80 333  90]]


In [54]:
# Deleting values from ndarray using numpy.delete() function
import numpy as np
arr = np.array([10,20,30,40,50,60])
print("Before deleting array item is =", arr)

# delete 30
arr = np.delete(arr,2)
print("After deleting array item is =", arr)

Before deleting array item is = [10 20 30 40 50 60]
After deleting array item is = [10 20 40 50 60]


In [56]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print("Before deleting array item is =", arr)

# Delete value 30 and 50 and 10 from 1D
arr = np.delete(arr,[2,4,0])
print("After deleting array item is =", arr)

Before deleting array item is = [10 20 30 40 50 60]
After deleting array item is = [20 40 60]


In [61]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Before deleting array item is =\n", arr)
print('-'*40)

# Delete 1 Row from 2D
arr = np.delete(arr,1,axis=0)
print("After deleting array item is =\n", arr)

Before deleting array item is =
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
----------------------------------------
After deleting array item is =
 [[10 20 30]
 [70 80 90]]


In [62]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Before deleting array item is =\n", arr)
print('-'*40)

# Delete 1 Column from 2D
arr = np.delete(arr,1,axis=1)
print("After deleting array item is =\n", arr)

Before deleting array item is =
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
----------------------------------------
After deleting array item is =
 [[10 30]
 [40 60]
 [70 90]]


In [63]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Before deleting array item is =\n", arr)
print('-'*40)

# Delete 0 Row and 2nd row from 2D
arr = np.delete(arr,[0,2],axis=0)
print("After deleting array item is =\n", arr)

Before deleting array item is =
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
----------------------------------------
After deleting array item is =
 [[40 50 60]]


In [64]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Before deleting array item is =\n", arr)
print('-'*40)

# Delete 0th and 1st column from 2D
arr = np.delete(arr,[0,1],axis=1)
print("After deleting array item is =\n", arr)

Before deleting array item is =
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
----------------------------------------
After deleting array item is =
 [[30]
 [60]
 [90]]


In [66]:
# Replace the Elements of ndarray object 
import numpy as np
arr = np.array([10,20,30,40,50])
print("Array is =", arr)

# replace 30 to 300
arr[2] = 300
print("Array after replace is =", arr)

Array is = [10 20 30 40 50]
Array after replace is = [ 10  20 300  40  50]


In [67]:
# Replace the Elements of ndarray object 
import numpy as np
arr = np.array([10,20,30,40,50])
print("Array is =", arr)

# replace 10 to 100, 30 to 300 and 50 to 500
arr[::2] = [100,300,500]
print("Array after replace is =", arr)

Array is = [10 20 30 40 50]
Array after replace is = [100  20 300  40 500]


In [73]:
# Replacing the 2d array items
import numpy as np
arr = np.array([10,20,30,40,50,60]).reshape(2,3)
print("Before replace array is =\n", arr)

# replace 10 to 100 and 40 to 400
arr[::,:1:] = [[100],[400]]
print("After replace array is =\n", arr)

Before replace array is =
 [[10 20 30]
 [40 50 60]]
After replace array is =
 [[100  20  30]
 [400  50  60]]


In [76]:
arr[1:,1:] = [500,600]
print(arr)

[[100  20  30]
 [400 500 600]]


In [78]:
arr[0:1:,1::] = [200,300]
print(arr)

[[100 200 300]
 [400 500 600]]


In [81]:
# replace courner elements to 1 2 3 4
arr[::,::2] = [[1,2],[3,4]]
print(arr)

[[  1 200   2]
 [  3 500   4]]


In [88]:
import numpy as np
arr = np.arange(100,1000,100).reshape(3,3)
print("Array is =\n", arr)
print('-'*50)

# replace courner items to 1,2,3,4
arr[::2,::2] = [[1,2],[3,4]]
print("After Replacing is :\n", arr)

Array is =
 [[100 200 300]
 [400 500 600]
 [700 800 900]]
--------------------------------------------------
After Replacing is :
 [[  1 200   2]
 [400 500 600]
 [  3 800   4]]


In [1]:
import numpy as np
arr = np.random.randint(1,9,size=(4,4))
print("Before replace array is :\n", arr)

# replace courner items with 1000,2000,3000,4000
arr[::3,::3] = [[1000,2000],[3000,4000]]
print("After replace array is :\n", arr)

Before replace array is :
 [[5 6 7 3]
 [2 1 1 6]
 [2 5 2 7]
 [4 5 2 7]]
After replace array is :
 [[1000    6    7 2000]
 [   2    1    1    6]
 [   2    5    2    7]
 [3000    5    2 4000]]
