In [1]:
import numpy as np
a=np.array(range(10,100,10))
print("content of a \n", a)
print("Dimension of a =", a.ndim)

content of a 
 [10 20 30 40 50 60 70 80 90]
Dimension of a = 1


In [4]:
# iterating on 1-D array using for loop
for val in a:
    print(val)

10
20
30
40
50
60
70
80
90


In [5]:
# iterating usig while loop
i=0
while i<(len(a)):
    print(a[i])
    i+=1

10
20
30
40
50
60
70
80
90


In [6]:
a=np.arange(1,10).reshape(3,3)
print("content of a \n", a)
print("Dimension of a =", a.ndim)

content of a 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of a = 2


In [7]:
# iterating on 2-D array using for loop
for row in a:
    for col in row:
        print(col)

1
2
3
4
5
6
7
8
9


In [9]:
# iterating on 2-D array using while loop
r=0
while r<(len(a)):
    c=0
    while c<(len(a[r])):
        print(a[r,c])
        c+=1
    else:
        r+=1

1
2
3
4
5
6
7
8
9


In [12]:
arr=np.arange(10,100,10).reshape(3,3)
print("content of array is =\n", arr)
print("Dimension of array is =", arr.ndim)
print('---------------------')
# iterating using while loop 
r=0
while r<(len(arr)):
    c=0
    while c<(len(arr[r])):
        print(arr[r,c])
        c+=1
    else:
        r+=1

content of array is =
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of array is = 2
---------------------
10
20
30
40
50
60
70
80
90


In [14]:
# iterating on 3-D array object
a=np.arange(3*3*3).reshape(3,3,3)
print("content of a =\n", a)
print("Dimension of a =", a.ndim)

content of a =
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension of a = 3


In [24]:
# using for loop
for mat in a:
    for row in mat:
        for col in row:
            print(col)
    print('----------')

0
1
2
3
4
5
6
7
8
----------
9
10
11
12
13
14
15
16
17
----------
18
19
20
21
22
23
24
25
26
----------


In [25]:
# iterating on 3-D array object using while loop
m=0
while m<(len(a)):
    r=0
    while r<(len(a[m])):
        c=0
        while c<(len(a[r])):
            print(a[m,r,c])
            c+=1
        else:
            r+=1
    else:
        m+=1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [26]:
a=np.array(range(10,100,5)).reshape(2,3,3)
print("content of a")
print(a)
print("Dim of a=",a.ndim)

content of a
[[[10 15 20]
  [25 30 35]
  [40 45 50]]

 [[55 60 65]
  [70 75 80]
  [85 90 95]]]
Dim of a= 3


In [29]:
for matrix in a:
    for row in matrix:
        for col in row:
            print(col)
        print('------------')
    print('========================') # matrix end

10
15
20
------------
25
30
35
------------
40
45
50
------------
55
60
65
------------
70
75
80
------------
85
90
95
------------


In [32]:
# now by using while loop
m=0
while m<(len(a)):
    r=0
    while r<(len(a[m])):
        c=0
        while c<(len(a[m,r])):
            print(a[m,r,c])
            c+=1
        else:
            print('---------------')
            r+=1
    else:
        print('=================')   # matrix end
        m+=1

10
15
20
---------------
25
30
35
---------------
40
45
50
---------------
55
60
65
---------------
70
75
80
---------------
85
90
95
---------------


In [ ]:
# By using numpy.nditer()
# Syntax:   for varname in numpy.nditer(ndarrayobj):
#                   Block of stmts 

In [33]:
import numpy as np
a=np.array(range(10,100,10))
print("content of a ", a)
print("Dimension of a =", a.ndim)

content of a  [10 20 30 40 50 60 70 80 90]
Dimension of a = 1


In [34]:
# using for loop
for val in np.nditer(a):
    print(val)

10
20
30
40
50
60
70
80
90


In [40]:
# iterating over 2-d array
a=np.arange(10,100,10).reshape(3,3)
print("content of a =\n", a)
print("Dimension of a =", a.ndim)
print('-------------------')
for value in np.nditer(a):
    print(value)

content of a =
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of a = 2
-------------------
10
20
30
40
50
60
70
80
90


In [42]:
# iterating over 3d array
a=np.arange(3*3*3).reshape(3,3,3)
print("content of a =\n", a)
print("Dimension of a =", a.ndim)
print('--------------')
for value in np.nditer(a):
    print(value)

content of a =
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension of a = 3
--------------
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
# By using numpy.ndenumerate()
# Syntax:   for varname1,varname2 in numpy.ndenumerate(ndarrayobj):
#                   Block of statements

In [43]:
import numpy as np
a=np.array(range(10,100,10))
print("content of a =", a)
print("Dimension of a =", a.ndim)

content of a = [10 20 30 40 50 60 70 80 90]
Dimension of a = 1


In [44]:
# using ndenumerate() we iteratering on 1-D array
for index,value in np.ndenumerate(a):
    print("{} => {}".format(index,value))

(0,) => 10
(1,) => 20
(2,) => 30
(3,) => 40
(4,) => 50
(5,) => 60
(6,) => 70
(7,) => 80
(8,) => 90


In [46]:
# using ndenumerate() we iteratering on 2-D array
a=np.arange(10,100,10).reshape(3,3)
print("content of a =\n", a)
print("Dimension of a =", a.ndim)
print('-----------------')
for index,value in np.ndenumerate(a):
    print("{} => {}".format(index,value))

content of a =
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of a = 2
-----------------
(0, 0) => 10
(0, 1) => 20
(0, 2) => 30
(1, 0) => 40
(1, 1) => 50
(1, 2) => 60
(2, 0) => 70
(2, 1) => 80
(2, 2) => 90


In [47]:
# print with row,column and values
for index,value in np.ndenumerate(a):
    print("Row:{} Col:{} => Value:{}".format(index[0],index[1],value))

Row:0 Col:0 => Value:10
Row:0 Col:1 => Value:20
Row:0 Col:2 => Value:30
Row:1 Col:0 => Value:40
Row:1 Col:1 => Value:50
Row:1 Col:2 => Value:60
Row:2 Col:0 => Value:70
Row:2 Col:1 => Value:80
Row:2 Col:2 => Value:90


In [51]:
# using ndenumerate() we iteratering on 3-D array
a=np.arange(27).reshape(3,3,3)
print("content of a =\n", a)
print("Dimension of a =", a.ndim)

content of a =
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension of a = 3


In [52]:
for index,value in np.ndenumerate(a):
    print("{} => {}".format(index,value))

(0, 0, 0) => 0
(0, 0, 1) => 1
(0, 0, 2) => 2
(0, 1, 0) => 3
(0, 1, 1) => 4
(0, 1, 2) => 5
(0, 2, 0) => 6
(0, 2, 1) => 7
(0, 2, 2) => 8
(1, 0, 0) => 9
(1, 0, 1) => 10
(1, 0, 2) => 11
(1, 1, 0) => 12
(1, 1, 1) => 13
(1, 1, 2) => 14
(1, 2, 0) => 15
(1, 2, 1) => 16
(1, 2, 2) => 17
(2, 0, 0) => 18
(2, 0, 1) => 19
(2, 0, 2) => 20
(2, 1, 0) => 21
(2, 1, 1) => 22
(2, 1, 2) => 23
(2, 2, 0) => 24
(2, 2, 1) => 25
(2, 2, 2) => 26


In [56]:
for index,value in np.ndenumerate(a):
    print("Matrix:{} Row:{} Column:{} => value:{}".format(index[0],index[1],index[2],value))

Matrix:0 Row:0 Column:0 => value:0
Matrix:0 Row:0 Column:1 => value:1
Matrix:0 Row:0 Column:2 => value:2
Matrix:0 Row:1 Column:0 => value:3
Matrix:0 Row:1 Column:1 => value:4
Matrix:0 Row:1 Column:2 => value:5
Matrix:0 Row:2 Column:0 => value:6
Matrix:0 Row:2 Column:1 => value:7
Matrix:0 Row:2 Column:2 => value:8
Matrix:1 Row:0 Column:0 => value:9
Matrix:1 Row:0 Column:1 => value:10
Matrix:1 Row:0 Column:2 => value:11
Matrix:1 Row:1 Column:0 => value:12
Matrix:1 Row:1 Column:1 => value:13
Matrix:1 Row:1 Column:2 => value:14
Matrix:1 Row:2 Column:0 => value:15
Matrix:1 Row:2 Column:1 => value:16
Matrix:1 Row:2 Column:2 => value:17
Matrix:2 Row:0 Column:0 => value:18
Matrix:2 Row:0 Column:1 => value:19
Matrix:2 Row:0 Column:2 => value:20
Matrix:2 Row:1 Column:0 => value:21
Matrix:2 Row:1 Column:1 => value:22
Matrix:2 Row:1 Column:2 => value:23
Matrix:2 Row:2 Column:0 => value:24
Matrix:2 Row:2 Column:1 => value:25
Matrix:2 Row:2 Column:2 => value:26


In [57]:
for index,value in np.ndenumerate(a):
    print("Matrix:{} Row:{} Column:{} => value:{}".format(index[-3],index[-2],index[-1],value))

Matrix:0 Row:0 Column:0 => value:0
Matrix:0 Row:0 Column:1 => value:1
Matrix:0 Row:0 Column:2 => value:2
Matrix:0 Row:1 Column:0 => value:3
Matrix:0 Row:1 Column:1 => value:4
Matrix:0 Row:1 Column:2 => value:5
Matrix:0 Row:2 Column:0 => value:6
Matrix:0 Row:2 Column:1 => value:7
Matrix:0 Row:2 Column:2 => value:8
Matrix:1 Row:0 Column:0 => value:9
Matrix:1 Row:0 Column:1 => value:10
Matrix:1 Row:0 Column:2 => value:11
Matrix:1 Row:1 Column:0 => value:12
Matrix:1 Row:1 Column:1 => value:13
Matrix:1 Row:1 Column:2 => value:14
Matrix:1 Row:2 Column:0 => value:15
Matrix:1 Row:2 Column:1 => value:16
Matrix:1 Row:2 Column:2 => value:17
Matrix:2 Row:0 Column:0 => value:18
Matrix:2 Row:0 Column:1 => value:19
Matrix:2 Row:0 Column:2 => value:20
Matrix:2 Row:1 Column:0 => value:21
Matrix:2 Row:1 Column:1 => value:22
Matrix:2 Row:1 Column:2 => value:23
Matrix:2 Row:2 Column:0 => value:24
Matrix:2 Row:2 Column:1 => value:25
Matrix:2 Row:2 Column:2 => value:26


In [58]:
# Using 4-D array for iterating
a=np.arange(16).reshape(2,2,2,2)
print("content of a =\n", a)
print("Dimension of a=", a.ndim)

content of a =
 [[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
Dimension of a= 4


In [59]:
# using nditer() method
for value in np.nditer(a):
    print(value,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

In [60]:
# using ndenumerate() method
for index,value in np.ndenumerate(a):
    print("Clauster:{} Matrix:{} Row:{} Column:{} => Value:{}".format(index[0],index[1],index[2],index[3],value))

Clauster:0 Matrix:0 Row:0 Column:0 => Value:0
Clauster:0 Matrix:0 Row:0 Column:1 => Value:1
Clauster:0 Matrix:0 Row:1 Column:0 => Value:2
Clauster:0 Matrix:0 Row:1 Column:1 => Value:3
Clauster:0 Matrix:1 Row:0 Column:0 => Value:4
Clauster:0 Matrix:1 Row:0 Column:1 => Value:5
Clauster:0 Matrix:1 Row:1 Column:0 => Value:6
Clauster:0 Matrix:1 Row:1 Column:1 => Value:7
Clauster:1 Matrix:0 Row:0 Column:0 => Value:8
Clauster:1 Matrix:0 Row:0 Column:1 => Value:9
Clauster:1 Matrix:0 Row:1 Column:0 => Value:10
Clauster:1 Matrix:0 Row:1 Column:1 => Value:11
Clauster:1 Matrix:1 Row:0 Column:0 => Value:12
Clauster:1 Matrix:1 Row:0 Column:1 => Value:13
Clauster:1 Matrix:1 Row:1 Column:0 => Value:14
Clauster:1 Matrix:1 Row:1 Column:1 => Value:15
