In [8]:
# Filtering the data from ndarray
import numpy as np
a=np.random.randint(2,20,size=6)
print("Content of a is =", a)

Content of a is = [ 6 10  6 12  5 19]


In [ ]:
# Procedure-1
# Step-1: Prepare a Condition(s) which gives boolean Array of type ndarray.
# step-2: Pass boolean array to ndarray object

In [9]:
barr=a%2==0
print(barr,type(barr))
print('--------------------')
a[barr]

[ True  True  True  True False False] <class 'numpy.ndarray'>
--------------------


array([ 6, 10,  6, 12], dtype=int32)

In [11]:
barr=a%2!=0
print(barr,type(barr))
print('-------------')
a[barr]

[False False False False  True  True] <class 'numpy.ndarray'>
-------------


array([ 5, 19], dtype=int32)

In [12]:
print(a)

[ 6 10  6 12  5 19]


In [15]:
# get the number are greater than 10
barr=a>10
a[barr]

array([12, 19], dtype=int32)

In [22]:
a=np.arange(27).reshape(3,3,3)
print("content of a =\n", a)
print("Dimension is =", a.ndim)
# Now get the multiple of 5
ba=a%5==0
print('------------------')
a[ba]

content of a =
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension is = 3
------------------


array([ 0,  5, 10, 15, 20, 25])

In [30]:
# Now get the multiple of 3 and 4
ba=a%3==0
bx=a%4==0
print("Multiple of 3 = :", a[ba])
print('----------------------------')
print("Multiple of 4 = :", a[bx])

Multiple of 3 = : [ 0  3  6  9 12 15 18 21 24]
----------------------------
Multiple of 4 = : [ 0  4  8 12 16 20 24]


In [31]:
# get mulitiple of 7
a[a%7==0]

array([ 0,  7, 14, 21])