In [8]:
# filtering the Data from ndarray---numpy.where()
import numpy as np
a=np.arange(10,21)
print("content of a =\n", a)
b=np.where(a%2==0)
print('--------------')
print(b,type(b))
print('--------------')
print(a[b],type(a))
print('--------------')
print("Even numbers :", a[b])
print("Odd numbers :", a[a%2!=0])

content of a =
 [10 11 12 13 14 15 16 17 18 19 20]
--------------
(array([ 0,  2,  4,  6,  8, 10]),) <class 'tuple'>
--------------
[10 12 14 16 18 20] <class 'numpy.ndarray'>
--------------
Even numbers : [10 12 14 16 18 20]
Odd numbers : [11 13 15 17 19]


In [17]:
a=np.random.randn(2,3)
print("content of a =\n", a)
print('-----------------------------')
# Replace all -ve values with 0 and +ve values keep them as it is
print("Filter data ")
b=np.where(a<0,0,a)
print(b)

content of a =
 [[ 0.82360807 -1.48599837 -0.30998895]
 [-0.93448155  0.38053409 -0.10469349]]
-----------------------------
Filter data 
[[0.82360807 0.         0.        ]
 [0.         0.38053409 0.        ]]


In [26]:
a1=np.random.randint(10,55,size=10)
a2=np.random.randint(35,55,size=10)
print("Array - 1 :", a1)
print("Array - 2 :", a2)
print('-------------------------')
# Get all the Elements which are more than 30 from both ndarray object
print("Elements More than 30 from both ndarray Objects ")
b=np.where(a1>30,a1,a2)
print(b)

Array - 1 : [36 32 19 11 42 50 16 16 32 21]
Array - 2 : [38 37 38 51 40 42 46 47 36 52]
-------------------------
Elements More than 30 from both ndarray Objects 
[36 32 38 51 42 50 46 47 32 52]


In [32]:
sal=np.array([1000,2000,3000,2000,4000,3000])
comm=np.array([10,15,None,15,None,None])
print("Salary List :", sal)
print("Commission List :", comm)
ncomm=np.where(comm==None,0,comm)
print("New comminsion List :", ncomm)

Salary List : [1000 2000 3000 2000 4000 3000]
Commission List : [10 15 None 15 None None]
New comminsion List : [10 15 0 15 0 0]


In [40]:
# Get Total Salaty of zip
print('-'*50)
print("Salary\t\tcomm\t\tTotal Salary")
print('-'*50)
for sal1,comm1 in zip(sal,ncomm):
    print(f"{sal1}\t\t{comm1}\t\t{sal1+comm1}")
print('-'*50)

In [45]:
# filtering scalar values
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.array([100,200,300,400,500,600,700,800,900,1000])
print(a)
print(b)
print('----------------')
c=np.where(a%2==0,'even','odd')
print(c)

[ 1  2  3  4  5  6  7  8  9 10]
[ 100  200  300  400  500  600  700  800  900 1000]
----------------
['odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even']


In [46]:
# Multiple conditional tests can be specified by passing the condition as a boolean array:
import numpy as np
a = np.array([1, 2, 3, 4])
criteria = (a < 2) | (a > 3)
np.where(criteria, 0, a)

array([0, 2, 3, 0])

In [54]:
# Filter the Data by using extract()
import numpy as np
a=np.random.randint(10,50,size=10)
print(a)
# get the narray of less than 20
print('------------------')
b=np.extract(a<20,a)
print("Less than 20 =",b)

[33 22 19 16 11 32 23 19 28 29]
------------------
Less than 20 = [19 16 11 19]


In [58]:
a=np.random.randint(10,55,size=20)
print(a)
# get the elements greater than 30
b=np.extract(a>30,a)
print("Greater than 30 =",b)

[47 44 42 22 17 35 10 15 23 17 50 14 45 41 29 37 44 16 25 46]
Greater than 30 = [47 44 42 35 50 45 41 37 44 46]


In [59]:
sal=np.array([1000,2000,3000,1500,500,5550])
comm=np.array([10,20,None,15,5,None])
print("Salary List :", sal)
print("Commision List :", comm)
print('--------------------')
only_comm=np.extract(comm!=None,comm)
print(only_comm)

Salary List : [1000 2000 3000 1500  500 5550]
Commision List : [10 20 None 15 5 None]
--------------------
[10 20 15 5]


In [88]:
a=np.random.randint(100,999,size=15)
print(a)
print("Total Items =", a.size)
# Take a values greater than 500
b=np.extract(a>500,a)
print("Greater than 500 =", b)
print("Number of items =", b.size)
print('-'*50)
# Take a values Less than 500
b=np.extract(a<500,a)
print("Less than 500 =", b)
print("Number of items =", b.size)

[620 284 898 928 625 289 582 672 582 720 459 181 768 579 488]
Total Items = 15
Greater than 500 = [620 898 928 625 582 672 582 720 768 579]
Number of items = 10
--------------------------------------------------
Less than 500 = [284 289 459 181 488]
Number of items = 5


In [5]:
import numpy as np
arr = np.arange(1,11)
print('Array is =', arr)

arr2 = np.where(arr<5,'even','odd')
print(arr2)

Array is = [ 1  2  3  4  5  6  7  8  9 10]
['even' 'even' 'even' 'even' 'odd' 'odd' 'odd' 'odd' 'odd' 'odd']
