In [3]:
# Numpy-Products 
import numpy as np
ar = np.array([1,2,3,4])
print("Array is :", ar)
x = np.prod(ar)
print("Product of array is =", x)

Array is : [1 2 3 4]
Product of array is = 24


In [4]:
arr = np.arange(1,10)
print("Array is :", arr)
pd = np.prod(arr)
print("Product is :", pd)

Array is : [1 2 3 4 5 6 7 8 9]
Product is : 362880


In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Array1 is =", arr1)
print("Array2 is =", arr2)
pd = np.prod([arr1,arr2])  # by default row wise multiplication is done
print("Product is :", pd)

Array1 is = [1 2 3]
Array2 is = [4 5 6]
Product is : 720


In [8]:
# Getting matrix column product
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("Array is =\n", arr)

# axis=0 represent column product
a = np.prod(arr,axis=0)
print("Product =", a)

Array is =
 [[1 2 3]
 [4 5 6]]
Product = [ 4 10 18]


In [13]:
# Getting matrix column product
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("Array is =\n", arr)

# axis=1 represent Rows product
a = np.prod(arr,axis=1)
print("Product =", a)

Array is =
 [[1 2 3]
 [4 5 6]]
Product = [  6 120]


In [12]:
import numpy as np
ar = np.arange(27).reshape(3,3,3)
print("Array matrix is =\n", ar)
print('-------------------')
pd = np.prod(ar,axis=0)
print("Product =\n", pd)

Array matrix is =
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-------------------
Product =
 [[   0  190  440]
 [ 756 1144 1610]
 [2160 2800 3536]]


In [14]:
import numpy as np
ar = np.arange(27).reshape(3,3,3)
print("Array matrix is =\n", ar)
print('-------------------')
pd = np.prod(ar,axis=1)
print("Product =\n", pd)

Array matrix is =
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-------------------
Product =
 [[    0    28    80]
 [ 1620  2080  2618]
 [ 9072 10450 11960]]


In [17]:
# Another example
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
print("Array1 =", a1)
print("Array2 =", a2)
pd = np.prod([a1,a2],axis=1)
print("Product =", pd)

Array1 = [1 2 3 4]
Array2 = [5 6 7 8]
Product = [  24 1680]


In [20]:
# Cummulative Product
import numpy as np
ar = np.array([1,2,3,4])
print("Array is =", ar)
cpd = np.cumprod(ar)
print("Cumulative product is :", cpd)

Array is = [1 2 3 4]
Cumulative product is : [ 1  2  6 24]


In [21]:
import numpy as np
arr = np.array([[1,2,3],[3,4,5],[2,3,5]])
print("Content of arr")
print(arr)
print("-------------------------")
x = np.cumprod(arr,axis=1) # Here axis=1 Represents Cumulative Row Product 
print(x)

Content of arr
[[1 2 3]
 [3 4 5]
 [2 3 5]]
-------------------------
[[ 1  2  6]
 [ 3 12 60]
 [ 2  6 30]]


In [22]:
import numpy as np
arr = np.array([[1,2,3],[3,4,5],[2,3,5]])
print("Content of arr")
print(arr)
print("-------------------------")
x = np.cumprod(arr,axis=0) # Here axis=0 Represents Cumulative Column Product
print(x)

Content of arr
[[1 2 3]
 [3 4 5]
 [2 3 5]]
-------------------------
[[ 1  2  3]
 [ 3  8 15]
 [ 6 24 75]]
