In [6]:
# Sorting of ndrray object
import numpy as np
a = np.random.randint(1,10,size=10)
print("content of array is =", a)

# Sort the Data of ndarray
a = np.sort(a)
print("Array after sorting =", a)

content of array is = [7 3 2 4 6 9 5 9 8 2]
Array after sorting = [2 2 3 4 5 6 7 8 9 9]


In [8]:
arr = np.sort(a)
print("Sorted array in Ascending array =")
print(arr)
print("Sorted array in Descending array =")
print(arr[::-1])

Sorted array in Ascending array =
[2 2 3 4 5 6 7 8 9 9]
Sorted array in Descending array =
[9 9 8 7 6 5 4 3 2 2]


In [16]:
# sorting 2d array
import numpy as np
ar = np.random.randint(1,100,size=(4,4))
print("content of array is =\n", ar)
print('--------------------')

# By deafult Row Wise
ar = np.sort(ar)
print("Sorted array is =\n", ar)

content of array is =
 [[67 87 49 40]
 [23 18 98 98]
 [30 26 40 44]
 [70 27 59 63]]
--------------------
Sorted array is =
 [[40 49 67 87]
 [18 23 98 98]
 [26 30 40 44]
 [27 59 63 70]]


In [19]:
# sorting the data in Row Wise
import numpy as np
ar = np.random.randint(1,100,size=(4,4))
print("content of array is =\n", ar)
print('--------------------') 

# axis=1 Represents Rows in the case sort()
ar = np.sort(ar,axis=1)
print("Row Wise sorted array is =")
print(ar)

content of array is =
 [[16 52 64 17]
 [51 46 13 27]
 [91 51 28 96]
 [ 1 50 81 43]]
--------------------
Row Wise sorted array is =
[[16 17 52 64]
 [13 27 46 51]
 [28 51 91 96]
 [ 1 43 50 81]]


In [20]:
# sorting the data in column Wise
import numpy as np
ar = np.random.randint(1,100,size=(4,4))
print("content of array is =\n", ar)
print('--------------------') 

# axis=0 Represents column in the case sort()
ar = np.sort(ar,axis=0)
print("Column Wise sorted array is =")
print(ar)

content of array is =
 [[56 93 82 67]
 [ 8 37 88  9]
 [31 98 38 16]
 [22 23 47 54]]
--------------------
Column Wise sorted array is =
[[ 8 23 38  9]
 [22 37 47 16]
 [31 93 82 54]
 [56 98 88 67]]


In [23]:
ar = np.sort(ar[::,:2:])
print(ar)

[[ 8 23]
 [22 37]
 [31 93]
 [56 98]]
