In [11]:
import numpy as np
a1=np.arange(10)
print("Array =", a1)
print("Type =", type(a1))
print('-----------------------')
print("Dimension =", a1.ndim)
a1.shape=(2,5)
print("shape =", a1.shape)
print("size =", a1.size)
print("Data type =", a1.dtype)
print("Item-size =", a1.itemsize)
print(a1)
print('-----------------------')



Array = [0 1 2 3 4 5 6 7 8 9]
Type = <class 'numpy.ndarray'>
-----------------------
Dimension = 1
shape = (2, 5)
size = 10
Data type = int64
Item-size = 8
[[0 1 2 3 4]
 [5 6 7 8 9]]
-----------------------


In [16]:
a2=np.arange(10,20)
print("Array =", a2)
print("shape =", a2.shape)
print("Type =", type(a2))
print("--------------------------")
print("Dimension =", a2.ndim)
a2.shape=(5,2)
print("shape =", a2.shape)
print("size =", a2.size)
print("Data type =", a2.dtype)
print("Item-size =", a2.itemsize) 
print(a2)

Array = [10 11 12 13 14 15 16 17 18 19]
shape = (10,)
Type = <class 'numpy.ndarray'>
--------------------------
Dimension = 1
shape = (5, 2)
size = 10
Data type = int64
Item-size = 8
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [19]:
a3=np.arange(10,110,10)
print("Array =", a3)
print("shape =", a3.shape)
print("Type =", type(a3))
print("--------------------------")
print("Dimension =", a3.ndim)
a3.shape=(2,5)
print("shape =", a3.shape)
print("size =", a3.size)
print("Data type =", a3.dtype)
print("Item-size =", a3.itemsize) 
print(a3)

Array = [ 10  20  30  40  50  60  70  80  90 100]
shape = (10,)
Type = <class 'numpy.ndarray'>
--------------------------
Dimension = 1
shape = (2, 5)
size = 10
Data type = int64
Item-size = 8
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [25]:
a4=np.arange(1,21,2).reshape(2,5)
print(a4)
print(type(a4))
print("Dimension =", a4.ndim)
print("shape =", a4.shape)
print("Size =", a4.size)
print("data type =", a4.dtype)
print("item-size =", a4.itemsize)

[[ 1  3  5  7  9]
 [11 13 15 17 19]]
<class 'numpy.ndarray'>
Dimension = 2
shape = (2, 5)
Size = 10
data type = int64
item-size = 8


In [28]:
a=np.arange(4*4).reshape(4,4)
print(a)
print(type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
<class 'numpy.ndarray'>


In [29]:
a=np.arange(3*4*4).reshape(3,4,4)
print(a)
print(type(a))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
<class 'numpy.ndarray'>


In [30]:
a=np.arange(4*4*4).reshape(4,4,4)
print(a)
print(type(a))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]
<class 'numpy.ndarray'>


In [34]:
a=np.arange(-1,-11,-1).reshape(2,5)
print(a,type(a))

[[ -1  -2  -3  -4  -5]
 [ -6  -7  -8  -9 -10]]


In [37]:
a=np.arange(100,9,-10).reshape(2,5)
print(a,type(a))

[[100  90  80  70  60]
 [ 50  40  30  20  10]]


In [41]:
a=np.arange(-5,6,1)
print(a,type(a))


[-5 -4 -3 -2 -1  0  1  2  3  4  5] <class 'numpy.ndarray'>
