In [2]:
# Numpy--Finding Unique Values
s = "MISSISSIPPI"
s1 = set(s)
print(''.join(s1))

MPIS


In [3]:
# Writing our own logical code
s = "MISSISSIPPI"
lst = []
for val in s:
    if val not in lst:
        lst.append(val)
print(''.join(lst))

MISP


In [5]:
# get the unique values from given list
lst1 = [10,20,30,10,20,40,30,50,60,10,20,30,60,70,80,90]
lst2 = []
for val in lst1:
    if val not in lst2:
        lst2.append(val)
print("Unique values of list 1")
print(lst2)

Unique values of list 1
[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [9]:
# Now finding the unique values from ndarray using numpy.unique() funtion
import numpy as np
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print("Original Array is =", arr)

# geting unique values
uq_val = np.unique(arr)
print("Unique values from array:", uq_val)
print("Number of unique values in array:", len(uq_val))

Original Array is = [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique values from array: [11 12 13 14 15 16 17 18]
Number of unique values in array: 8


In [14]:
# Now getting unique and their first index position of Numpy Array
import numpy as np
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print("Original array is :", arr)
print("Original array length is :", len(arr))
print('-----------------')

# Get a tuple of unique values & their first index location from a numpy array
unq, ind = np.unique(arr,return_index=True)
print("Unique values are :", unq)
print("Indexes are :", ind)

Original array is : [11 11 12 13 14 15 16 17 12 13 11 14 18]
Original array length is : 13
-----------------
Unique values are : [11 12 13 14 15 16 17 18]
Indexes are : [ 0  2  3  4  5  6  7 12]


In [17]:
import numpy as np
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print("Original array is :", arr)
print("Original array length is :", len(arr))
print('----------------------------------')

# get two values in tuple format
tup = np.unique(arr,return_index=True)
print(type(tup))
print("Unique values are :", tup[0])
print("Indexes are :", tup[1])

Original array is : [11 11 12 13 14 15 16 17 12 13 11 14 18]
Original array length is : 13
----------------------------------
<class 'tuple'>
Unique values are : [11 12 13 14 15 16 17 18]
Indexes are : [ 0  2  3  4  5  6  7 12]


In [22]:
# formating data using for loop
print('-'*40)
uq,ind = np.unique(arr,return_index=True)
for uq,ind in zip(uq,ind):
    print("{} at index -> {}".format(uq,ind))
print('-'*40)

# We can also get it like this
uq,ind = np.unique(arr,return_index=True)
for tup in zip(uq,ind):
    print("{} at index -> {}".format(tup[0],tup[1]))

----------------------------------------
11 at index -> 0
12 at index -> 2
13 at index -> 3
14 at index -> 4
15 at index -> 5
16 at index -> 6
17 at index -> 7
18 at index -> 12
----------------------------------------
11 at index -> 0
12 at index -> 2
13 at index -> 3
14 at index -> 4
15 at index -> 5
16 at index -> 6
17 at index -> 7
18 at index -> 12


In [25]:
# Our own code for geting frequency count of ndarray elements
lst = [11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18]
print("Original list is :", lst)
lst1 = []
for val in lst:
    if val not in lst1:
        lst1.append(val)

# Now printing thier counts/frequency
for val in lst1:
    print("{} freq is -> {}".format(val,lst.count(val)))

Original list is : [11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18]
11 freq is -> 3
12 freq is -> 2
13 freq is -> 2
14 freq is -> 2
15 freq is -> 1
16 freq is -> 1
17 freq is -> 1
18 freq is -> 1


In [26]:
# Now getting unique values and frequency count of ndarray elements using unique() function
import numpy as np
arr = [11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18]
print("Original Array is :", arr)
print('-'*40)

unq,fre = np.unique(arr, return_counts=True)
print("Unique values :", unq)
print("Frequency is :", fre)

Original Array is : [11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18]
----------------------------------------
Unique values : [11 12 13 14 15 16 17 18]
Frequency is : [3 2 2 2 1 1 1 1]


In [29]:
# We can also get it
tup = np.unique(arr, return_counts=True)
print("Unique values :", tup[0])
print("Frequency is :", tup[1])
print('-'*50)

# formatting output using for loop
for tp in zip(tup[0],tup[1]):
    print("{} freq is -> {}".format(tp[0],tp[1]))

Unique values : [11 12 13 14 15 16 17 18]
Frequency is : [3 2 2 2 1 1 1 1]
--------------------------------------------------
11 freq is -> 3
12 freq is -> 2
13 freq is -> 2
14 freq is -> 2
15 freq is -> 1
16 freq is -> 1
17 freq is -> 1
18 freq is -> 1


In [32]:
# Getting All the values of array unique, index, and their frequency counts
import numpy as np
arr = [11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18]
print("Original Array is :", arr)
print('-'*50)

uq,ind,fre = np.unique(arr,return_index=True,return_counts=True)
print("Unique values are :", uq)
print("Indexes in original array :", ind)
print("Frequency is :", fre)

Original Array is : [11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18]
--------------------------------------------------
Unique values are : [11 12 13 14 15 16 17 18]
Indexes in original array : [ 0  2  3  4  5  6  7 12]
Frequency is : [3 2 2 2 1 1 1 1]


In [34]:
tup = np.unique(arr,return_index=True,return_counts=True)
print("Unique values are :", tup[0])
print("Indexes in original array :", tup[1])
print("Frequency is :", tup[2])
print('-'*40)

# We get also like this
for tp in zip(tup[0],tup[1],tup[2]):
    print("{} index is -> {} and freq -> {}".format(tp[0],tp[1],tp[2]))

Unique values are : [11 12 13 14 15 16 17 18]
Indexes in original array : [ 0  2  3  4  5  6  7 12]
Frequency is : [3 2 2 2 1 1 1 1]
----------------------------------------
11 index is -> 0 and freq -> 3
12 index is -> 2 and freq -> 2
13 index is -> 3 and freq -> 2
14 index is -> 4 and freq -> 2
15 index is -> 5 and freq -> 1
16 index is -> 6 and freq -> 1
17 index is -> 7 and freq -> 1
18 index is -> 12 and freq -> 1


In [39]:
# Find unique values, rows & columns in a 2D numpy array
# Create a 2D numpy array
import numpy as np
arr2D = np.array([[11, 11, 12,11] ,[ 13, 11, 12,11] , [ 16, 11, 12, 11],  [11, 11, 12, 11]])
print("Original 2D Array :\n", arr2D)
print('-'*40)

# get the unique value of default flattened array
unq = np.unique(arr2D)
print("Unique value is :", unq)

Original 2D Array :
 [[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]]
----------------------------------------
Unique value is : [11 12 13 16]


In [44]:
# Getting Rows values using axis=0 attributes 
import numpy as np
arr2D = np.array([[11, 11, 12,11] ,[ 13, 11, 12,11] , [ 16, 11, 12, 11],  [11, 11, 12, 11]])
print("Original 2D Array :\n", arr2D)
print('-'*40)

# get the unique value of rows in 2d array
unq = np.unique(arr2D,axis=0)
print("Unique Rows is :\n", unq)

Original 2D Array :
 [[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]]
----------------------------------------
Unique Rows is :
 [[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]]


In [45]:
# Getting Columns values using axis=1 attributes 
import numpy as np
arr2D = np.array([[11, 11, 12,11] ,[ 13, 11, 12,11] , [ 16, 11, 12, 11],  [11, 11, 12, 11]])
print("Original 2D Array :\n", arr2D)
print('-'*40)

# get the unique value of Columns in 2d array
unq = np.unique(arr2D,axis=1)
print("Unique Columns is :\n", unq)

Original 2D Array :
 [[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]]
----------------------------------------
Unique Columns is :
 [[11 11 12]
 [11 13 12]
 [11 16 12]
 [11 11 12]]
