In [2]:
# NumPy--- Discrete Differences
# A discrete difference means subtracting two successive elements.
import numpy as np
a = np.array([1,2,3,4])
print("Array is =", a)
df = np.diff(a)
print("Difference is =", df)

Array is = [1 2 3 4]
Difference is = [1 1 1]


In [5]:
b = np.array([10,15,25,5])
print("Array is =", b)
df = np.diff(b)
print("Difference is =", df)

# if we give n=2 then see result depth
df = np.diff(b,n=2)
print("Difference is =", df)

Array is = [10 15 25  5]
Difference is = [  5  10 -20]
Difference is = [  5 -30]


In [7]:
ar = np.array([[1,2,3],[3,4,5],[2,3,5]])
print("Array is =\n", ar)

# Here axis=0 Represents Column Discrete Diff
df = np.diff(ar,axis=0)
print("Difference is =\n", df)

Array is =
 [[1 2 3]
 [3 4 5]
 [2 3 5]]
Difference is =
 [[ 2  2  2]
 [-1 -1  0]]


In [9]:
ar = np.array([[1,2,3],[3,4,5],[2,3,5]])
print("Array is =\n", ar)

# Here axis=1 Represents Rows Discrete Diff
df = np.diff(ar,axis=1)
print("Difference is =\n", df)

Array is =
 [[1 2 3]
 [3 4 5]
 [2 3 5]]
Difference is =
 [[1 1]
 [1 1]
 [1 2]]


In [10]:
ar = np.array([[1,2,3],[3,4,5],[2,3,5]])
print("Array is =\n", ar)

# Here axis=0 Represents Column Discrete Diff
df = np.diff(ar,n=2,axis=0)
print("Difference is =\n", df)

Array is =
 [[1 2 3]
 [3 4 5]
 [2 3 5]]
Difference is =
 [[-3 -3 -2]]


In [12]:
ar = np.array([[1,2,3],[3,4,5],[2,3,5]])
print("Array is =\n", ar)

# Here axis=1 Represents Rows Discrete Diff
df = np.diff(ar,n=2,axis=1)
print("Difference is =\n", df)

Array is =
 [[1 2 3]
 [3 4 5]
 [2 3 5]]
Difference is =
 [[0]
 [0]
 [1]]


In [15]:
import numpy as np
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array is =\n", ar)

# find difference
df = np.diff(ar,axis=0)
print("Difference is =\n", df)

Array is =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Difference is =
 [[3 3 3]
 [3 3 3]]


In [17]:
import numpy as np
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array is =\n", ar)

# find difference
df = np.diff(ar,n=2,axis=0)
print("Difference is =\n", df)

Array is =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Difference is =
 [[0 0 0]]


In [18]:
import numpy as np
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array is =\n", ar)

# find difference
df = np.diff(ar,axis=1)
print("Difference is =\n", df)

Array is =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Difference is =
 [[1 1]
 [1 1]
 [1 1]]


In [19]:
import numpy as np
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array is =\n", ar)

# find difference
df = np.diff(ar,n=2,axis=1)
print("Difference is =\n", df)

Array is =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Difference is =
 [[0]
 [0]
 [0]]
