In [ ]:
# Numpy Matrix Operations

In [4]:
# Matrix addition by using add()
import numpy as np
A = np.array([[10,20,30],[40,50,60],[70,80,90]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix A:")
print(A)
print("Dimension of A =", A.ndim)
print('-'*50)
print("Matrix B:")
print(B)
print("Dimension of B =", B.ndim)
print('-'*50)
# Syntax: varname=numpy.add(ndarrayobj1, ndarrayob2)
C = np.add(A,B)
print("Addition of Matrix is :")
print(C)
print('-'*50)

Matrix A:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of A = 2
--------------------------------------------------
Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of B = 2
--------------------------------------------------
Addition of Matrix is :
[[11 22 33]
 [44 55 66]
 [77 88 99]]
--------------------------------------------------


In [5]:
# This addition is also done by using arithematic operator +
c = A + B
print(C)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [7]:
# Matrix Substraction by using subtract()
import numpy as np
A = np.array([[10,20,30],[40,50,60],[70,80,90]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix A:")
print(A)
print("Dimension of A =", A.ndim)
print('-'*50)
print("Matrix B:")
print(B)
print("Dimension of B =", B.ndim)
print('-'*50)
# Syntax: varname=numpy.subtract(ndarrayobj1, ndarrayob2)
C = np.subtract(A,B)
print("Subtraction of Matrix is :")
print(C)

Matrix A:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of A = 2
--------------------------------------------------
Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of B = 2
--------------------------------------------------
Subtraction of Matrix is :
[[ 9 18 27]
 [36 45 54]
 [63 72 81]]


In [8]:
# This subtraction is also done by using arithmatic operator -
C = A - B
print(C)

[[ 9 18 27]
 [36 45 54]
 [63 72 81]]


In [9]:
# Matrix Elemen twise Multiplication by using multiply()
import numpy as np
A = np.array([[10,20,30],[40,50,60],[70,80,90]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix A:")
print(A)
print("Dimension of A =", A.ndim)
print('-'*50)
print("Matrix B:")
print(B)
print("Dimension of B =", B.ndim)
print('-'*50)
# Syntax: varname=numpy.multiply(ndarrayobj1, ndarrayobj2)
C = A * B
print("Multiplication of matrix is :")
print(C)

Matrix A:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of A = 2
--------------------------------------------------
Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of B = 2
--------------------------------------------------
Multiplication of matrix is :
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


In [10]:
# This multiplication can be done by using arithematic operator *
C = A * B
print(C)

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


In [13]:
# Actual Matrix Multiplication by using numpy.dot() function
import numpy as np
A = np.array([10,20,30])
B = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print("Matrix A :\n", A)
print('--------------------')
print("Matrix B :\n", B)
print('--------------------')
C = np.dot(A,B)
print("Actual Matrix Multiplication =")
print(C)

Matrix A :
 [10 20 30]
--------------------
Matrix B :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
Actual Matrix Multiplication =
[300 360 420]


In [15]:
# This operation is also done by using another method numpy.matmul()
print("Matrix Multiplication by matmul()")
C = np.matmul(A,B)
print(C)

Matrix Multiplication by matmul()
[300 360 420]


In [18]:
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])
print("Matrix A is =\n",a)
print('-'*30)
print("Matrix B is =\n",b)
print('-'*30)
print("Multiply by dot() function")
c = np.dot(a,b)
print(c)
print('-'*30)
print("Multiply by matmul() function")
c = np.matmul(a,b)
print(c)

Matrix A is =
 [[10 20]
 [30 40]]
------------------------------
Matrix B is =
 [[1 2]
 [3 4]]
------------------------------
Multiply by dot() function
[[ 70 100]
 [150 220]]
------------------------------
Multiply by matmul() function
[[ 70 100]
 [150 220]]


In [20]:
# Real Example
ppu = np.array([1000,400,1200])
nus = np.array([[30,40,50],[5,10,15],[2,5,7]])
print("Price per unit")
print(ppu)
print('-'*30)
print("Number of Units Sold")
print(nus)
print('-'*30)
print("Total Sales Made")
sales = np.dot(ppu,nus)
print(sales)

Price per unit
[1000  400 1200]
------------------------------
Number of Units Sold
[[30 40 50]
 [ 5 10 15]
 [ 2  5  7]]
------------------------------
Total Sales Made
[34400 50000 64400]


In [22]:
# Matrix Division by using divide()
import numpy as np
A = np.array([[10,20,30],[40,50,60],[70,80,90]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix A:")
print(A)
print("Dimension of A =", A.ndim)
print('-'*50)
print("Matrix B:")
print(B)
print("Dimension of B =", B.ndim)
print('-'*50)
C = np.divide(A,B)
print("Matrix division is =")
print(C)

Matrix A:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of A = 2
--------------------------------------------------
Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of B = 2
--------------------------------------------------
Matrix division is =
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [23]:
# This matrix division is also done by using arimathmatic operator /
C = A / B
print("Matrix division is =\n",C)

Matrix division is =
 [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [24]:
# Matrix floor Division by using floor_divison() function
import numpy as np
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix A:")
print(a)
print("Dimension of A =", a.ndim)
print('-'*50)
print("Matrix B:")
print(b)
print("Dimension of B =", b.ndim)
print('-'*50)
c = np.floor_divide(a,b)
print("Floor division of matrix is =")
print(c)

Matrix A:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of A = 2
--------------------------------------------------
Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of B = 2
--------------------------------------------------
Floor division of matrix is =
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [27]:
# This operation also done by using arithmatic operator //
c = a // b
print("Floor division of matrix is =")
print(c)

Floor division of matrix is =
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [26]:
# Matrix element wise modulas operation using numpy.mod()
import numpy as np
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix A:")
print(a)
print("Dimension of A =", a.ndim)
print('-'*50)
print("Matrix B:")
print(b)
print("Dimension of B =", b.ndim)
print('-'*50)
c = np.mod(a,b)
print("Matrix Modulo operation ")
print(c)

Matrix A:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of A = 2
--------------------------------------------------
Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of B = 2
--------------------------------------------------
Matrix Modulo operation 
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [28]:
# This operation is also done by using arithematic operator %
c = a % b
print("Matrix modulo operation =")
print(c)

Matrix modulo operation =
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [31]:
# Matrix Element wise expontential operation is done by using numpy.power() function
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])
print("Matrix A =")
print(a)
print('-'*30)
print("Matrix B =")
print(b)
print('-'*30)
c = np.power(a,b)
print("Exponential of matrix is =")
print(c)

Matrix A =
[[10 20]
 [30 40]]
------------------------------
Matrix B =
[[1 2]
 [3 4]]
------------------------------
Exponential of matrix is =
[[     10     400]
 [  27000 2560000]]


In [32]:
# This operation is also done by using arthmatic operator **
c = a ** b
print("Matrix Exponetial is =")
print(c)

Matrix Exponetial is =
[[     10     400]
 [  27000 2560000]]


In [33]:
for i in range(1,6):
    for j in range(i):
        print("*",end=' ')
    print()

* 
* * 
* * * 
* * * * 
* * * * * 


In [40]:
space = 0
for i in range(1,6):
    for sp in range(space):
        print(" ",end=' ')
    space += 1
    for j in range(i,6):
        print("*",end=' ')
    print()

* * * * * 
  * * * * 
    * * * 
      * * 
        * 
