In [ ]:
# Splitting NumPy 2D Arrays

In [5]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
print("Content of a \n", a)
print("Dimension of a :", a.ndim)

Content of a 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of a : 2


In [16]:
# axis = 0 means rows and axis = 1 means columns
res1 = np.split(a,3,axis=0)
print(res1)
print('--------------------------')
res2 = np.split(a,3,axis=1)
print(res2)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
--------------------------
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [27]:
a = np.random.randint(10,60,size=(3,3))
print(a)
print('-----------------------')
# getting rows and columns using slicing
print("First Row =", a[0:1:,::])
print("Second Row =", a[1:2:,::])
print("Third Row =", a[2::,::])
print('-----------------------')
print("First Column = \n", a[::,0:1:])
print("Second Column = \n", a[::,1:2:])
print("Third Column = \n", a[::,2::])

[[52 10 13]
 [41 43 59]
 [53 44 10]]
-----------------------
First Row = [[52 10 13]]
Second Row = [[41 43 59]]
Third Row = [[53 44 10]]
-----------------------
First Column = 
 [[52]
 [41]
 [53]]
Second Column = 
 [[10]
 [43]
 [44]]
Third Column = 
 [[13]
 [59]
 [10]]


In [33]:
# Creating an example matrix--numpy.vsplit(ndarrayobject,splitsize)
a = np.array(range(10,100,10)).reshape(3,3)
print("Content of a =\n", a)
print('-------------------')
res = np.vsplit(a,3)
print(res)

Content of a =
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
-------------------
[array([[10, 20, 30]]), array([[40, 50, 60]]), array([[70, 80, 90]])]


In [40]:
a = np.array(range(1,13)).reshape(4,3)
print("Content of a =\n", a)
print("Dimension of a =", a.ndim)
print('-----------------------')
res = np.vsplit(a,2)
for mat in res:
    print(mat)
    print('-----------')

Content of a =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Dimension of a = 2
-----------------------
[[1 2 3]
 [4 5 6]]
-----------
[[ 7  8  9]
 [10 11 12]]
-----------


In [43]:
# Example of numpy.hsplit()
arr = np.array(range(1,13)).reshape(3,4)
print("Content of array =\n", arr)
print("Dimension of array =", arr.ndim)
print('-------------------')
# spliting the array in horizontal direction
result = np.hsplit(arr,2)
for k in result:
    print(k)
    print('---------------')

Content of array =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimension of array = 2
-------------------
[[ 1  2]
 [ 5  6]
 [ 9 10]]
---------------
[[ 3  4]
 [ 7  8]
 [11 12]]
---------------


In [47]:
# Now taking the 3d array example
a = np.array(range(1,25)).reshape(2,3,4)
print("Content of a =\n", a)
print("Dimension of a =", a.ndim)
print('------------------------')
result = np.dsplit(a,2)
for mat in result:
    print(mat)
    print('-----------')

Content of a =
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Dimension of a = 3
------------------------
[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[13 14]
  [17 18]
  [21 22]]]
-----------
[[[ 3  4]
  [ 7  8]
  [11 12]]

 [[15 16]
  [19 20]
  [23 24]]]
-----------


In [52]:
# implementing dsplit() mechanism using slicing
a = np.arange(24).reshape(2,3,4)
print("content of a =\n", a)
print('----------------------')
print(a[::,::,0:2:])
print('----------------------')
print(a[::,::,2::])

content of a =
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
----------------------
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[12 13]
  [16 17]
  [20 21]]]
----------------------
[[[ 2  3]
  [ 6  7]
  [10 11]]

 [[14 15]
  [18 19]
  [22 23]]]


In [60]:
arr = np.array(range(1,10)).reshape(3,3)
print(arr)
res = np.hsplit(arr,3)
for r in res:
    print(r)
    print('---------')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [4]
 [7]]
---------
[[2]
 [5]
 [8]]
---------
[[3]
 [6]
 [9]]
---------
