# In This file we practice the flatten() and ravel()

In [11]:
# flatten() 
import numpy as np
a1 = np.arange(1,7).reshape(2,3)
print("content 2d array =\n", a1)
print("Dimension of 2d array is =", a1.ndim)
print('-'*50)

# now convert into flatten array
a2 = a1.flatten()
print("content 2d array =\n", a2)
print("Dimension of 2d array is =", a2.ndim)

content 2d array =
 [[1 2 3]
 [4 5 6]]
Dimension of 2d array is = 2
--------------------------------------------------
content 2d array =
 [1 2 3 4 5 6]
Dimension of 2d array is = 1


In [14]:
# update the orginal array
a1[0,0] = 10
print("content of a1 is =\n", a1)
print("Dimension of a1 is =", a1.ndim)
print('----------')

# check the flattend array
print("content 2d array =\n", a2)
print("Dimension of 2d array is =", a2.ndim)

content of a1 is =
 [[10  2  3]
 [ 4  5  6]]
Dimension of a1 is = 2
----------
content 2d array =
 [1 2 3 4 5 6]
Dimension of 2d array is = 1


In [16]:
# update the flattend array
a2[-1] = 99
print("content of flattend array is =\n", a2)
print("Dimension of flattend array is =", a2.ndim)
print('----------')

# check the flattend array
print("content original array =\n", a1)
print("Dimension o foriginal array is =", a1.ndim)

content of flattend array is =
 [ 1  2  3  4  5 99]
Dimension of flattend array is = 1
----------
content original array =
 [[10  2  3]
 [ 4  5  6]]
Dimension o foriginal array is = 2


In [23]:
# ravel()
import numpy as np
org = np.arange(1,7).reshape(2,3)
print("Original array is =\n", org)
print("Dimension of array is =", org.ndim)
print('------------------')

# convert into flattend using raval() funtion
rav = org.ravel()
print("Ravel array is =\n", rav)
print("Dimension of array is =", rav.ndim)

Original array is =
 [[1 2 3]
 [4 5 6]]
Dimension of array is = 2
------------------
Ravel array is =
 [1 2 3 4 5 6]
Dimension of array is = 1


In [27]:
# update original array
org[0,0] = 1000
print("Original array is =\n", org)
print("Dimension of array is =", org.ndim)
print('----------------------')

# check the reveled array changes are done or not
print("Ravel array is =\n", rav)
print("Dimension of array is =", rav.ndim)

Original array is =
 [[1000    2    3]
 [   4    5    6]]
Dimension of array is = 2
----------------------
Ravel array is =
 [1000    2    3    4    5    6]
Dimension of array is = 1


In [30]:
# update ravel array
rav[-1] = 986
print("Ravel array is =\n", rav)
print("Dimension of array is =", rav.ndim)
print('-----------------------')

# check the changed are made in original array or not
print("Original array is =\n", org)
print("Dimension of array is =", org.ndim)

Ravel array is =
 [1000    2    3    4    5  986]
Dimension of array is = 1
-----------------------
Original array is =
 [[1000    2    3]
 [   4    5  986]]
Dimension of array is = 2
