In [1]:
# implementing linear algebra equations
import numpy as np
a = np.array([[2,3],[1,1]])
b = np.array([6,3])
print("Content of a is =\n", a)
print("Content of b is =", b)
sol = np.linalg.solve(a,b)
print(sol)

Content of a is =
 [[2 3]
 [1 1]]
Content of b is = [6 3]
[ 3. -0.]


In [3]:
# solve the following
# 2x+5y=20
# 3x+6y=12
import numpy as np
a = np.array([[2,5],[3,6]])
b = np.array([20,12])
print("Content of array1 =\n", a)
print("Content of array2 =", b)
print('-------------------')
sol = np.linalg.solve(a,b)
print("solution is =", sol)
print("Value of x =", sol[0])
print("Value of y =", sol[1])

Content of array1 =
 [[2 5]
 [3 6]]
Content of array2 = [20 12]
-------------------
solution is = [-20.  12.]
Value of x = -20.0
Value of y = 12.0


In [5]:
# solve the following linear equations
# 8x + 7y = 38 and 3x - 5y = - 1.
import numpy as np
ar1 = np.array([[8,7],[3,-5]])
ar2 = np.array([38,-1])
print("Array1 is =\n", ar1)
print("Array2 is =", ar2)
print('------------------')
sol = np.linalg.solve(ar1,ar2)
print("Value of x =", sol[0])
print("Value of y =", sol[1])

Array1 is =
 [[ 8  7]
 [ 3 -5]]
Array2 is = [38 -1]
------------------
Value of x = 3.0
Value of y = 2.0


In [6]:
# solve the following linear equations
# 2x + 5y = 20 
# 3x + 6y = 12
import numpy as np
arr1 = np.array([[2,5],[3,6]])
arr2 = np.array([20,12])
print("Array1 is =\n", arr1)
print("Array2 is =", arr2)
print('-------------------')
sol = np.linalg.solve(arr1,arr2)
print("solution is =", sol)
print("Value of x =", sol[0])
print("Value of y =", sol[1])

Array1 is =
 [[2 5]
 [3 6]]
Array2 is = [20 12]
-------------------
solution is = [-20.  12.]
Value of x = -20.0
Value of y = 12.0


In [12]:
# Solve the Following equations
# 3x+4y+5z=5
# 6x+3y+3z=4
# x+y+z=8
# Find x , y and z
import numpy as np
arr1 = np.array([[3,4,5],[6,3,3],[1,1,1]])
arr2 = np.array([5,4,8])
print("Array1 is =\n", arr1)
print("Array2 is =", arr2)
print('-------------------')
sol = np.linalg.solve(arr1,arr2)
print("Solution is =", sol)
print('-------------------')
print("Value of x is =", round(sol[0],2))
print("Value of y is =", round(sol[1],2))
print("Value of z is =", round(sol[2],2))

Array1 is =
 [[3 4 5]
 [6 3 3]
 [1 1 1]]
Array2 is = [5 4 8]
-------------------
Solution is = [ -6.66666667  48.33333333 -33.66666667]
-------------------
Value of x is = -6.67
Value of y is = 48.33
Value of z is = -33.67


In [14]:
# use of dot() to perform array multiplication
import numpy as np
a = np.array([1,3,5])
b = np.array([2,4,6])
print("Matrix1 is =", a)
print("Matrix2 is =", b)
print('----------------')
dt = np.dot(a,b)
print("Dot product of two matrix is =", dt)

Matrix1 is = [1 3 5]
Matrix2 is = [2 4 6]
----------------
Dot product of two matrix is = 44


In [18]:
import numpy as np
arr1 = np.array([[1, 3],[5, 7]])
arr2 = np.array([[2, 4],[6, 8]])
print("Array1 = \n", arr1)
print("Array2 = \n", arr2)
print('------------------')
# inner() for 2D arrays
ar = np.inner(arr1,arr2)
print("Inner Multiplication is =")
print(ar)

Array1 = 
 [[1 3]
 [5 7]]
Array2 = 
 [[2 4]
 [6 8]]
------------------
Inner Multiplication is =
[[14 30]
 [38 86]]


In [19]:
arr1 = np.array([1,3,5])
arr2 = np.array([2,4,6])
print("Array1 =", arr1)
print("Array2 =", arr2)
print('------------------')
# Outer() for 2D arrays
ar = np.outer(arr1,arr2)
print("Outer multiplication is =")
print(ar)

Array1 = [1 3 5]
Array2 = [2 4 6]
------------------
Outer multiplication is =
[[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]


In [20]:
arr1 = np.array([2,4,8])
arr2 = np.array([6,7,9])
print("Array1 =", arr1)
print("Array2 =", arr2)
print('------------------')
# Outer() for 2D arrays
ar = np.outer(arr1,arr2)
print("Outer multiplication is =")
print(ar)

Array1 = [2 4 8]
Array2 = [6 7 9]
------------------
Outer multiplication is =
[[12 14 18]
 [24 28 36]
 [48 56 72]]


In [21]:
import numpy as np
arr1 = np.array([[1, 3],[5, 7]])
arr2 = np.array([[2, 4],[6, 8]])
print("Array1 = \n", arr1)
print("Array2 = \n", arr2)
print('------------------')
# outer() for 2D arrays
ar = np.outer(arr1,arr2)
print("Inner Multiplication is =")
print(ar)

Array1 = 
 [[1 3]
 [5 7]]
Array2 = 
 [[2 4]
 [6 8]]
------------------
Inner Multiplication is =
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [23]:
# divmod() function example
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
print("Array1 =", arr1)
print("Array2 =", arr2)
dm = np.divmod(arr1,arr2)
print(dm)
print('---------------------')
print("Quotient array is =", dm[0])
print("Remainder array is =", dm[1])

Array1 = [10 20 30 40 50 60]
Array2 = [ 3  7  9  8  2 33]
(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))
---------------------
Quotient array is = [ 3  2  3  5 25  1]
Remainder array is = [ 1  6  3  0  0 27]


In [24]:
# Absolute Values of array
arr1 = np.array([-1, -2, 1, 2, 3, -4])
print("original array is =", arr1)
print('-------------------')
print("Absoulte values array is =", np.absolute(arr1))

original array is = [-1 -2  1  2  3 -4]
-------------------
Absoulte values array is = [1 2 1 2 3 4]


In [28]:
# power() function example
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,2,2,2,2])
print("Array1 is =", arr1)
print("Array2 is =", arr2)
pw = np.power(arr1,arr2)
print(pw)

Array1 is = [1 2 3 4 5]
Array2 is = [2 2 2 2 2]
[ 1  4  9 16 25]


In [33]:
# determinant --> det() example
# => ad - bc of matrix
import numpy as np
arr = np.array([[4,2],[1,2]])
print("Array is =\n", arr)
print('--------------------')
d = np.linalg.det(arr)
print("Determinant of matrix is =", d)

Array is =
 [[4 2]
 [1 2]]
--------------------
Determinant of matrix is = 6.0


In [36]:
# ineverse of matrix
import numpy as np
arr = np.array([[2,4],[6,8]])
print("Array is =\n", arr)
inv = np.linalg.inv(arr)
print("Inverse of matrix is =\n", inv)

Array is =
 [[2 4]
 [6 8]]
Inverse of matrix is =
 [[-1.    0.5 ]
 [ 0.75 -0.25]]


In [37]:
# trace() do the Addition of diagonal elements of matrix
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array1 is =\n", arr)
trc = np.trace(arr)
print("Addition of diagonal elements =", trc)

Array1 is =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Multiply of diagonal elements = 15


In [39]:
import numpy as np
arr = np.random.randint(1,10,size=(4,4))
print("Array is =\n", arr)
trc = np.trace(arr)
print("Addition of diagonal elements is =", trc)

Array is =
 [[8 2 2 1]
 [5 6 2 9]
 [6 4 1 6]
 [1 7 7 6]]
Multiplication of diagonal elements is = 21
