In [1]:
# NumPy Set Operations
import numpy as np
arr = np.random.randint(1,10,size=20)
print(arr,type(arr))

# create a set means convert ndarray into set using unique method
st = np.unique(arr)
print(st)

[2 9 7 7 4 5 9 5 6 4 7 8 6 8 8 4 9 8 8 4] <class 'numpy.ndarray'>
[2 4 5 6 7 8 9]


In [11]:
# Finding Union using union1d array
import numpy as np
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
print(a1,a2)
x = np.union1d(a1,a2)
print("Union is =",x)

[1 2 3 4] [5 6 7 8]
[1 2 3 4 5 6 7 8]


In [16]:
# Finding Intersection using intersect1d()
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])
print(arr1,arr2)
x = np.intersect1d(arr1,arr2, assume_unique=True) # it is an optional parameter
print("Intersection is =",x)

[1 2 3 4] [3 4 5 6]
[3 4]


In [5]:
# Finding Difference using setdiff1d(set1,set2)
ar1 = np.array([1,2,3,4])
ar2 = np.array([3,4,5,6])
print(ar1,ar2)
d = np.setdiff1d(ar1,ar2)   # remove common elements and return remaning elements
print("Difference is =",d)

[1 2 3 4] [3 4 5 6]
Difference is = [1 2]


In [4]:
ar1 = np.array([1,2,3,4])
ar2 = np.array([3,4,5,6])
print(ar1,ar2)
df = np.setdiff1d(ar2,ar1)
print("Difference is =",df)

[1 2 3 4] [3 4 5 6]
Difference is = [5 6]


In [22]:
# Finding Symmetric Difference using setxor1d()
ar1 = np.array([1,2,3,4])
ar2 = np.array([3,4,5,6])
print(ar1,ar2)
sy = np.setxor1d(ar1,ar2)
print("Symmetric difference =", sy)

[1 2 3 4] [3 4 5 6]
Symmetric difference = [1 2 5 6]


In [7]:
ar1 = np.random.randint(10,15,size=5)
ar2 = np.random.randint(10,15,size=5)
print("Array1 is =", ar1)
print("Array2 is =", ar2)
df = np.setdiff1d

Array1 is = [11 14 14 12 13]
Array2 is = [11 13 10 12 11]
