In [3]:
# Numpy--Statiststical Operations
import numpy as np
a = np.array([10,23,17,19,20,30,45,13,56])
print("content of ndarray :")
print(a)

# Finding the maximum value using numpy.amax() function
val1 = np.amax(a)
print("Maximum value of ndarray is =", val1)

# finding the minimum value using numpy.amin() function
val2 = np.amin(a)
print("Minimum value of ndarray is =", val2)

content of ndarray :
[10 23 17 19 20 30 45 13 56]
Maximum value of ndarray is = 56
Minimum value of ndarray is = 10


In [8]:
# finding the min and max value on 2D-array
import numpy as np
a = np.array([8,20,10,23,16,9,7,56,43,35,29,13]).reshape(3,4)
print("content of 2D array is =\n", a)

# finding min and max value on entire array
min_val = np.amin(a)
print("Minimum value of 2d array =", min_val)

max_val = np.amax(a)
print("Maximum value of 2d array =", max_val)

content of 2D array is =
 [[ 8 20 10 23]
 [16  9  7 56]
 [43 35 29 13]]
Minimum value of 2d array = 7
Maximum value of 2d array = 56


In [11]:
# finding rows-wise and column-wise min and max values
# Axis = 1 represent Rows
# Axis = 0 represent Column

a = np.array([8,20,10,23,16,9,7,56,43,35,29,13]).reshape(3,4)
print("content of 2D array is =\n", a)
print('-'*40)

row_min = np.amin(a,axis=1)
row_max = np.amax(a,axis=1)
print("Row min =", row_min)
print("Row max =", row_max)
print('-'*40)

col_min = np.amin(a,axis=0)
col_max = np.amax(a,axis=0)
print("Column min =", col_min)
print("Column max =", col_max)

content of 2D array is =
 [[ 8 20 10 23]
 [16  9  7 56]
 [43 35 29 13]]
----------------------------------------
Row min = [ 8  7 13]
Row max = [23 56 43]
----------------------------------------
Column min = [ 8  9  7 13]
Column max = [43 35 29 56]


In [13]:
# finding the mean of ndarray elements
import numpy as np
a = np.array([10,20,30,40,50,2,3,4])
print("content of ndarray is=\n",a)

mn = np.mean(a)
print("Mean of ndarry =", mn)

content of ndarray is=
 [10 20 30 40 50  2  3  4]
Mean of ndarry = 19.875


In [16]:
# By finding our own python code
s = 0
for val in a:
    s += val
else:
    print("Mean is :", (s/len(a)))

Mean is : 19.875


In [20]:
# finding the mean of 2d array object
import numpy as np
arr = np.array([10,20,30,40,50,2,3,4,7]).reshape(3,3)
print("content of array is =\n", arr)
mn = np.mean(arr)
print("Mean of 2d array:", round(mn,2))

content of array is =
 [[10 20 30]
 [40 50  2]
 [ 3  4  7]]
Mean of 2d array: 18.44


In [23]:
# Find mean of samples of ndarray with 2-D along Row and Column
import numpy as np
arr = np.array([10,20,30,40,50,2,3,4,7]).reshape(3,3)
print("content of array is =\n", arr)

# for rows
row_mn = np.mean(arr,axis=1)
print("Rows mean =", row_mn)

# for columns
col_mn = np.mean(arr,axis=0)
print("Column mean =", col_mn)

content of array is =
 [[10 20 30]
 [40 50  2]
 [ 3  4  7]]
Rows mean = [20.         30.66666667  4.66666667]
Column mean = [17.66666667 24.66666667 13.        ]


In [25]:
# Find median of sample of ndarray with 1-D
import numpy as np
arr = np.array([20,10,40,30,15,25,3,4,7])
print("content of array is :\n", arr)

# using numpy.median() function
mdn = np.median(arr)
print("Median of array is =", mdn)

content of array is :
 [20 10 40 30 15 25  3  4  7]
Median of array is = 15.0


In [29]:
import numpy as np
arr = np.array([20,10,40,30,15,25,3,4,56,7])
print("content of array is :\n", arr)

# using numpy.median() function
mdn = np.median(arr)
print("Median of array is =", mdn)

content of array is :
 [20 10 40 30 15 25  3  4 56  7]
Median of array is = 17.5


In [30]:
# Find median of sample of ndarray with 2-D
import numpy as np
arr = np.array([20,10,40,30,15,25,3,4,7,22,19,72]).reshape(3,4)
print("content of 2d array is :\n", arr)

mdn = np.median(arr)
print("Median of 2D array is =", mdn)

content of 2d array is :
 [[20 10 40 30]
 [15 25  3  4]
 [ 7 22 19 72]]
Median of 2D array is = 19.5


In [5]:
import numpy as np
arr = np.array([20,10,40,30,15,25,3,4,7,22,19,72]).reshape(3,4)
print("content of array is :\n", arr)

# row-wise and column-wise median
row_mdn = np.median(arr,axis=1)
col_mdn = np.median(arr,axis=0)

print("Row Wise median is :", row_mdn)
print("Column Wise median is :", col_mdn)

content of array is :
 [[20 10 40 30]
 [15 25  3  4]
 [ 7 22 19 72]]
Row Wise median is : [25.   9.5 20.5]
Column Wise median is : [15. 22. 19. 30.]


In [12]:
# Calulating the variance of ndarray
import numpy as np
arr = np.array([2,4,1,3])
print("content of array is :", arr)

vr = np.var(arr)
print("Variance of ndarray is =", vr)

content of array is : [2 4 1 3]
Variance of ndarray is = 1.25


In [13]:
arr = np.array([2,4,1,3])
print("content of array is :", arr)
print("Mean is =", np.mean(arr))

content of array is : [2 4 1 3]
Mean is = 2.5


In [19]:
import numpy as np
heights = np.array([610, 450, 160, 420, 310])
print("Heights of students =\n", heights)

mn = np.mean(heights)
print("Mean/Average height is =", mn)

vr = np.var(heights)
print("Variance of heights is =", vr)

Heights of students =
 [610 450 160 420 310]
Mean/Average height is = 390.0
Variance of heights is = 22440.0


In [21]:
# calculating the standard deviation
import numpy as np
coines = np.array([4, 2, 5, 8, 6])
print("Gold coines pirets are =", coines)

vr = np.var(coines)
print("Variance is =", vr)

std = np.std(coines)
print("Standard deviation is =", std)

Gold coines pirets are = [4 2 5 8 6]
Variance is = 4.0
Standard deviation is = 2.0


In [23]:
lst = [4, 2, 5, 8, 6]
print(lst)
s = 0
for i in lst:
    s+=i
print("avg =", (s/len(lst)))

[4, 2, 5, 8, 6]
avg = 5.0


In [26]:
# calculate the variance and standrad deviation of given data
import numpy as np
dt = np.array([5, 10, 25, 30, 50])
print("Given Data is =", dt)

vr = np.var(dt)
print("Variance is =", vr)

std = np.std(dt)
print("Standard deviation is =", round(std,2))

Given Data is = [ 5 10 25 30 50]
Variance is = 254.0
Standard deviation is = 15.94


In [30]:
# calculate the variance and standrad deviation of given data
import numpy as np
dt = np.array([1, 4, 7, 2, 6])
print("Given data is =", dt)

vr = np.var(dt)
print("Variance is =", vr)

std = np.std(dt)
print("Standard deviation is =", round(std,3))

Given data is = [1 4 7 2 6]
Variance is = 5.2
Standard deviation is = 2.28


In [34]:
dt = [1, 4, 7, 2, 6]
print(dt)
s = 0
for i in dt:
    s += i
print("Mean =", (s/len(dt)))

[1, 4, 7, 2, 6]
Mean = 4.0


In [41]:
#Calcatulate Variance for the samples
a = np.array([145,155,157,163,149,161,175,165,168,172])
print("Given data is =", a)

vr = np.var(a)
print("Variance is =", vr)

std = np.std(a)
print("Standrad deviation is =", round(std,3))

Given data is = [145 155 157 163 149 161 175 165 168 172]
Variance is = 83.8
Standrad deviation is = 9.154


In [45]:
# Appliying on 2d array
arr = np.array([2,4,1,3]).reshape(2,2)
print("2d array is =\n", arr)

vr = np.var(arr)
print("Variance is =", vr)

std = np.std(arr)
print("Standard deviation is =", round(std,2))

2d array is =
 [[2 4]
 [1 3]]
Variance is = 1.25
Standard deviation is = 1.12


In [46]:
# calculating row and column wise var & std
import numpy as np
arr = np.array([2,4,1,3]).reshape(2,2)
print("2d array is =\n", arr)
print('-'*40)

row_var = np.var(arr,axis=1)
col_var = np.var(arr,axis=0)
print("Row variance is =", row_var)
print("Column variance is =", col_var)
print('-'*40)

row_std = np.std(arr,axis=1)
col_std = np.std(arr,axis=0)
print("Row standard deviation is =", row_std)
print("Column standard deviation is =", col_std)

2d array is =
 [[2 4]
 [1 3]]
----------------------------------------
Row variance is = [1. 1.]
Column variance is = [0.25 0.25]
----------------------------------------
Row standard deviation is = [1. 1.]
Column standard deviation is = [0.5 0.5]


In [49]:
a=np.array([2,4,1,3]).reshape(2,2)
print("Array is =\n",a)
print("std=",np.std(a))
print("Std Row Varianace=",np.std(a,axis=1))
print("Std Col Varianace=",np.std(a,axis=0))

Array is =
 [[2 4]
 [1 3]]
std= 1.118033988749895
Std Row Varianace= [1. 1.]
Std Col Varianace= [0.5 0.5]
