In [4]:
import numpy as np
a=np.zeros(10)
print(a,type(a))
print("Data type:", a.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>
Data type: float64


In [9]:
a=np.zeros(10,dtype=int)
print(a,type(a))
print("Data type:", a.dtype)
print("Dimension :", a.ndim)

[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>
Data type: int64
Dimension : 1


In [10]:
a=np.zeros((3,3),dtype=int)
print(a)
print("Dimension :", a.ndim)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Dimension : 2


In [12]:
a=np.zeros((4,4,4),dtype=int)
print(a)
print("Dimension :", a.ndim)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
Dimension : 3


In [5]:
import numpy as np
a=np.zeros((2,3,3),dtype=float)
print(a,type(a))
print("Dimension =", a.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]] <class 'numpy.ndarray'>
Dimension = 3


In [7]:
a=np.zeros((2,4,2),dtype=int)
print(a,type(a))
print("Dimension =", a.ndim)

[[[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]] <class 'numpy.ndarray'>
Dimension = 3


In [11]:
import numpy as np
a=np.ones(6)
print("-"*40)
print("Content of a :")
print(a)
print(type(a))
print("Data type is =", a.dtype)
print("Shape =", a.shape)
print("Size =", a.size)
print("Item-size =", a.itemsize)
print("-"*40)

Content of a :
[1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
Data type is = float64
Shape = (6,)
Size = 6
Item-size = 8


In [15]:
a=np.ones((3,3),dtype=int)
print("-"*40)
print("Content of a :")
print(a)
print(type(a))
print("Data type is =", a.dtype)
print("Shape =", a.shape)
print("Size =", a.size)
print("Item-size =", a.itemsize)
print("-"*40)

Content of a :
[[1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
Data type is = int64
Shape = (3, 3)
Size = 9
Item-size = 8


In [24]:
a=np.ones((16),dtype=int)
print("-"*40)
print("Content of a :")
print(a)
print(type(a))
print("Element data type is =", a.dtype)
print("Content of a after reshaping")
a.shape=(4,2,2)
print(a)
print("Shape is =", a.shape)
print("Size =", a.size)
print("Item-size =", a.itemsize)
print("-"*40)

----------------------------------------
Content of a :
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
<class 'numpy.ndarray'>
Element data type is = int64
Content of a after reshaping
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
Shape is = (4, 2, 2)
Size = 16
Item-size = 8
----------------------------------------


In [30]:
a=np.ones(10,dtype=str)
print(a)
print("Element data type :", a.dtype)
print("Shape =", a.shape)
print("Dimension =", a.ndim)
print("="*50)
a.shape=(5,2)
print(a)
print("Shape =", a.shape)
print("Dimension =", a.ndim)

['1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
Element data type : <U1
Shape = (10,)
Dimension = 1
[['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']]
Shape = (5, 2)
Dimension = 2
