# Numpy---Random Permutations of Elements

In [5]:
# Numpy---Random Permutations of Elements---shuffle()
import numpy as np
arr = np.arange(1,6)
print("Given Data is =")
print(arr, id(arr))
np.random.shuffle(arr)
print("Shuffled data is =")
print(arr, id(arr))

Given Data is =
[1 2 3 4 5] 2172068404976
Shuffled data is =
[5 1 2 4 3] 2172068404976


In [8]:
import numpy as np
arr = np.arange(1,6)
print("Given Data is =")
print(arr, id(arr))

for i in range(1,len(arr)+1):
    np.random.shuffle(arr)
    print("{} Times shuffled data -> {}".format(i,arr))

Given Data is =
[1 2 3 4 5] 2172077866128
1 Times shuffled data -> [1 4 2 3 5]
2 Times shuffled data -> [4 2 3 1 5]
3 Times shuffled data -> [1 2 5 3 4]
4 Times shuffled data -> [1 3 5 2 4]
5 Times shuffled data -> [5 1 3 2 4]


In [11]:
# Numpy---Random Permutations of Elements---permutation()
arr = np.array([1,2,3,4,5])
print("Given data is =", arr)
x = np.random.permutation(arr)
print("One possiable permutation is =", x)

Given data is = [1 2 3 4 5]
One possiable permutation is = [2 3 1 5 4]


In [12]:
import numpy as np
arr = np.array([1,2,3,4,5])
print("Given data is =", arr)

for i in range(1,len(arr)+1):
    x = np.random.permutation(arr)
    print("{} Times possiable permutation is --> {}".format(i,x))

Given data is = [1 2 3 4 5]
1 Times possiable permutation is --> [3 5 2 1 4]
2 Times possiable permutation is --> [3 1 4 2 5]
3 Times possiable permutation is --> [3 4 1 5 2]
4 Times possiable permutation is --> [3 1 2 4 5]
5 Times possiable permutation is --> [4 2 1 3 5]


# Summation of array in numpy

In [20]:
import numpy as np
a = np.array([1,2,3])
b = np.array([1,2,3])
print("Martix-1 {}\nMatrix-2 {}".format(a,b))
print('--------------------')

c = np.add(a,b)
print("Add is =", c)
print('--------------------')

sm = np.sum([a,b])
print("Summation is =", sm)

Martix-1 [1 2 3]
Matrix-2 [1 2 3]
--------------------
Add is = [2 4 6]
--------------------
Summation is = 12


In [25]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print("Matrix-1 : {}".format(arr1))
print("Matrix-1 : {}".format(arr2))
print('----------------')
sm = np.sum([arr1,arr2],axis=1)
print("Summation is =", sm)

Matrix-1 : [1 2 3]
Matrix-1 : [1 2 3]
----------------
Summation is = [6 6]


In [28]:
import numpy as np
arr1 = np.array([[1, 2, 3],[10,20,30]])
arr2 = np.array([[1, 2, 3],[-2,-2,-2]])
print("Matrix-1 : \n{}".format(arr1))
print("Matrix-2 : \n{}".format(arr2))
print('-----------------------')
newarr = np.sum([arr1, arr2],axis=0)
print(newarr) 

Matrix-1 : 
[[ 1  2  3]
 [10 20 30]]
Matrix-2 : 
[[ 1  2  3]
 [-2 -2 -2]]
-----------------------
[[ 2  4  6]
 [ 8 18 28]]


In [35]:
# Cummulative Sum of matrix
# Cummulative sum means partially adding the elements in array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print('-----------')
new_arr = np.cumsum(arr)
print(new_arr)

[1 2 3 4 5]
-----------
[ 1  3  6 10 15]


In [36]:
# Another example
import numpy as np
arr = np.array([10,20,30,40,50])
print("Original array is =", arr)
print('-----------------')
print("Cummulative summation is =", np.cumsum(arr))

Original array is = [10 20 30 40 50]
-----------------
Cummulative summation is = [ 10  30  60 100 150]


In [32]:
# Numpy column insertion in 2D array
import numpy as np
arr = np.arange(1,10).reshape(3,3)
print(arr)
print('--------------')
arr = np.insert(arr,3,[[10,20,30]],axis=1)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------
[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


In [34]:
# insert row in matrix
a = np.arange(9).reshape(3,3)
print(a)
print('-------------')
a = np.insert(a,3,[9,10,11],axis=0)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
