In [ ]:
# Create an ndarray using eye() method
# varname=numpy.eye(N, M=None, k=0, dtype=float)

In [2]:
import numpy as np
a=np.eye(3,dtype=int)
print(a)
print(type(a))
print('-'*50)
print("Dimension =", a.ndim)
print("shape =", a.shape)
print("Size =", a.size)
print("Element data type =", a.dtype)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
<class 'numpy.ndarray'>
--------------------------------------------------
Dimension = 2
shape = (3, 3)
Size = 9
Element data type = int64


In [14]:
a=np.eye(3,6,k=-1,dtype=int)
print(a)
print(type(a))
print('-'*50)
print("Dimension =", a.ndim)
print("shape =", a.shape)
print("Size =", a.size)
print("Element data type =", a.dtype)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]]
<class 'numpy.ndarray'>
--------------------------------------------------
Dimension = 2
shape = (3, 6)
Size = 18
Element data type = int64


In [7]:
a=np.eye(3,6,k=-2,dtype=int)
print(a)
print(type(a))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]]
<class 'numpy.ndarray'>


In [10]:
a=np.eye(3,6,k=2,dtype=int)
print(a)
print(type(a))

[[0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]
<class 'numpy.ndarray'>


In [11]:
a=np.eye(3,6,k=3,dtype=int)
print(a)
print(type(a))

[[0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
<class 'numpy.ndarray'>


In [12]:
a=np.eye(3,6,k=4,dtype=int)
print(a)
print(type(a))

[[0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]
<class 'numpy.ndarray'>


In [13]:
a=np.eye(3,6,k=5,dtype=int)
print(a)
print(type(a))

[[0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
<class 'numpy.ndarray'>


In [22]:
a=np.eye(4,5,dtype=int)
print(a)
print(type(a))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]
<class 'numpy.ndarray'>


In [34]:
a=np.eye(2,3,k=1,dtype=int)
print(a)
print(type(a))


[[0 1 0]
 [0 0 1]]
<class 'numpy.ndarray'>


In [40]:
a=np.eye(3,2,k=-1,dtype=int)
print(a)
print(type(a))

[[0 0]
 [1 0]
 [0 1]]
<class 'numpy.ndarray'>


In [47]:
a=np.eye(6,2,k=-4,dtype=int)
print(a)
print(type(a))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]]
<class 'numpy.ndarray'>


In [49]:
a=np.eye(6,k=0,dtype=int)
print(a)
print(type(a))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
<class 'numpy.ndarray'>


In [50]:
a=np.eye(6,k=-6,dtype=int)
print(a)
print(type(a))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
<class 'numpy.ndarray'>


In [51]:
a=np.eye(6,k=-4,dtype=int)
print(a)
print(type(a))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]]
<class 'numpy.ndarray'>


In [53]:
a=np.eye(6,k=1,dtype=int)
print(a)
print(type(a))

[[0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
<class 'numpy.ndarray'>


In [54]:
a=np.eye(6,k=2,dtype=int)
print(a)
print(type(a))

[[0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
<class 'numpy.ndarray'>


In [55]:
a=np.eye(6,k=3,dtype=int)
print(a)
print(type(a))

[[0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
<class 'numpy.ndarray'>


jello
