In [ ]:
# In this notebook examples are based on full() and identity() methods
# varname=numpy.full(shape,fill_value,dtype)

In [5]:
import numpy as np
a=np.full(6,3)
print(a)
print(type(a))
print("Shape =", a.shape)
print("Size =", a.size)
print("Dimension =", a.ndim)
print("Element data type =", a.dtype)

[3 3 3 3 3 3]
<class 'numpy.ndarray'>
Shape = (6,)
Size = 6
Dimension = 1
Element data type = int64


In [6]:
a=np.full(6,3,dtype=float)
print(a)
print(type(a))
print("Shape =", a.shape)
print("Size =", a.size)
print("Dimension =", a.ndim)
print("Element data type =", a.dtype)

[3. 3. 3. 3. 3. 3.]
<class 'numpy.ndarray'>
Shape = (6,)
Size = 6
Dimension = 1
Element data type = float64


In [13]:
a=np.full((2,8),22,dtype=int)
print(a)
print(type(a))
print("Shape =", a.shape)
print("Size =", a.size)
print("Dimension =", a.ndim)
print("Element data type =", a.dtype)

[[22 22 22 22 22 22 22 22]
 [22 22 22 22 22 22 22 22]]
<class 'numpy.ndarray'>
Shape = (2, 8)
Size = 16
Dimension = 2
Element data type = int64


In [22]:
a=np.full((3,3),fill_value='A',dtype=str)
print(a)
print(type(a))
print("Shape =", a.shape)
print("Size =", a.size)
print("Dimension =", a.ndim)
print("Element data type =", a.dtype)

[['A' 'A' 'A']
 ['A' 'A' 'A']
 ['A' 'A' 'A']]
<class 'numpy.ndarray'>
Shape = (3, 3)
Size = 9
Dimension = 2
Element data type = <U1


In [24]:
print('-'*50)
a=np.full((4,3,3),fill_value='A',dtype=str)
print(a)
print(type(a))
print("Shape =", a.shape)
print("Size =", a.size)
print("Dimension =", a.ndim)
print("Element data type =", a.dtype)
print('-'*50)

--------------------------------------------------
[[['A' 'A' 'A']
  ['A' 'A' 'A']
  ['A' 'A' 'A']]

 [['A' 'A' 'A']
  ['A' 'A' 'A']
  ['A' 'A' 'A']]

 [['A' 'A' 'A']
  ['A' 'A' 'A']
  ['A' 'A' 'A']]

 [['A' 'A' 'A']
  ['A' 'A' 'A']
  ['A' 'A' 'A']]]
<class 'numpy.ndarray'>
Shape = (4, 3, 3)
Size = 36
Dimension = 3
Element data type = <U1
--------------------------------------------------


In [30]:
a=np.full(6,fill_value=2,dtype=float)
print(a)
print(type(a))
print("shape =", a.shape)
print("element data type=", a.dtype)
a.shape=(2,3)
print(a)
print("Shape =", a.shape)

[2. 2. 2. 2. 2. 2.]
<class 'numpy.ndarray'>
shape = (6,)
element data type= float64
[[2. 2. 2.]
 [2. 2. 2.]]
Shape = (2, 3)


In [34]:
print("-"*50)
a=np.full((4,4),fill_value=5)
print(a)
print("Shape =", a.shape)
a.shape=(4,2,2)
print(a)
print("Shape =", a.shape)
print("-"*50)

--------------------------------------------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape = (4, 4)
[[[5 5]
  [5 5]]

 [[5 5]
  [5 5]]

 [[5 5]
  [5 5]]

 [[5 5]
  [5 5]]]
Shape = (4, 2, 2)
--------------------------------------------------


In [ ]:
# We can see now the identity matrix by by using numpy.identity()
# varname=numpy.identity(N,dtype)

In [42]:
a=np.identity(3,dtype=int)
print(a)
print(type(a))
print("Element data type :", a.dtype)
print("shape =", a.shape)
print("Dimension =", a.ndim)
print("Size =", a.size)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
<class 'numpy.ndarray'>
Element data type : int64
shape = (3, 3)
Dimension = 2
Size = 9


In [45]:
print("-"*50)
a=np.identity(9,dtype=int)
print(a)
print(type(a))
print("Element data type :", a.dtype)
print("shape =", a.shape)
print("Dimension =", a.ndim)
print("Size =", a.size)
print("-"*50)

--------------------------------------------------
[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]]
<class 'numpy.ndarray'>
Element data type : int64
shape = (9, 9)
Dimension = 2
Size = 81
--------------------------------------------------


In [ ]:
# We can see now linespace() in ndarray
# varname = numpy.linspace(start, stop, num, endpoint, retstep, dtype)   

In [50]:
a=np.linspace(1,5)
print(a)
print(type(a))
print('-'*50)
print("Shape =", a.shape)
print("Dimension =", a.ndim)

[1. 3. 5.]
<class 'numpy.ndarray'>
--------------------------------------------------
Shape = (3,)
Dimension = 1


In [54]:
a=np.linspace(1,5,num=3,endpoint=True)
print(a)
print(type(a))
print('-'*50)
print("Shape =", a.shape)
print("Dimension =", a.ndim)

[1. 3. 5.]
<class 'numpy.ndarray'>
--------------------------------------------------
Shape = (3,)
Dimension = 1


In [60]:
a=np.linspace(1,5,num=3,endpoint=True,retstep=False,dtype=int)
print(a)
print(type(a))
print('-'*50)
print("Shape =", a.shape)
print("Dimension =", a.ndim)
print("Element data type =", a.dtype)

[1 3 5]
<class 'numpy.ndarray'>
--------------------------------------------------
Shape = (3,)
Dimension = 1
Element data type = int64


In [63]:
a=np.linspace(1,5,num=2,endpoint=False,dtype=int)
print(a)
print('-'*50)
print("Shape =", a.shape)
print("Dimension =", a.ndim)
print("Element data type =", a.dtype)

[1 3]
--------------------------------------------------
Shape = (2,)
Dimension = 1
Element data type = int64


In [71]:
a=np.linspace(1,2,num=10,endpoint=False)
print(a)
print("Shape =", a.shape)
a=a.reshape(5,2)
print(a)
print("Shape =", a.shape)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
Shape = (10,)
[[1.  1.1]
 [1.2 1.3]
 [1.4 1.5]
 [1.6 1.7]
 [1.8 1.9]]
Shape = (5, 2)


In [78]:
a,rs=np.linspace(1,5,num=10,endpoint=False,retstep=True)
print(a)
print("retstep =", rs)

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6]
retstep = 0.4
