In [ ]:
# Creating an object of ndarray using hstack()
# Syntax: varname=numpy.hstack( (ndarrayobj1,ndarrayob2 ) )

In [1]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a,type(a))
print(b,type(b))

[1 2 3 4] <class 'numpy.ndarray'>
[5 6 7 8] <class 'numpy.ndarray'>


In [2]:
c=np.hstack((a,b))
print(c,type(c))

[1 2 3 4 5 6 7 8] <class 'numpy.ndarray'>


In [3]:
c=np.hstack((b,a))
print(c)
print(type(c))

[5 6 7 8 1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
a=np.arange(1,11).reshape(5,2)
b=np.arange(11,21).reshape(5,2)
print(a,type(a))
print('-'*50)
print(b,type(b))
print('-'*50)
c=np.hstack((a,b))
print(c,type(c))
print('-'*50)
d=np.hstack((b,a))
print(d,type(d))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] <class 'numpy.ndarray'>
--------------------------------------------------
[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]] <class 'numpy.ndarray'>
--------------------------------------------------
[[ 1  2 11 12]
 [ 3  4 13 14]
 [ 5  6 15 16]
 [ 7  8 17 18]
 [ 9 10 19 20]] <class 'numpy.ndarray'>
--------------------------------------------------
[[11 12  1  2]
 [13 14  3  4]
 [15 16  5  6]
 [17 18  7  8]
 [19 20  9 10]] <class 'numpy.ndarray'>


In [9]:
print("Shape of c=", c.shape)
print("Size of c=", c.size)

Shape of c= (5, 4)
Size of c= 20


In [10]:
print("Shape of d=", d.shape)
print("Size of c=", c.size)

Shape of d= (5, 4)
Size of c= 20


In [19]:
a=np.arange(3*4).reshape(3,4)
print("Matrix A")
print(a)
print(type(a))
print('-'*50)
b=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matrix B")
print(b)
print(type(b))
# margging the two array using hstack()
print('-'*50)
c=np.hstack((a,b))
print("Matrix C")
print(c,type(c))
print("Dimension =", c.ndim)
print("Shape =", c.shape)
print("Size =", c.size)

Matrix A
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
<class 'numpy.ndarray'>
--------------------------------------------------
Matrix B
[[10 20 30]
 [40 50 60]
 [70 80 90]]
<class 'numpy.ndarray'>
--------------------------------------------------
Matrix C
[[ 0  1  2  3 10 20 30]
 [ 4  5  6  7 40 50 60]
 [ 8  9 10 11 70 80 90]] <class 'numpy.ndarray'>
Dimension = 2
Shape = (3, 7)
Size = 21


In [24]:
a=np.array(range(0,9)).reshape(3,3)
b=np.array(range(10,16)).reshape(3,2)
d=np.array(range(101,103))
print(a,type(a))
print(b,type(b))
print(d,type(d))
print('-'*50)
c=np.hstack((a,b,c))
print(c,type(c))
print("Dimension =", c.ndim)
print("Shape =", c.shape)
print("Size =", c.size)
print("Element data type =", c.dtype)

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>
[[10 11]
 [12 13]
 [14 15]] <class 'numpy.ndarray'>
[101 102] <class 'numpy.ndarray'>
--------------------------------------------------
[[ 0  1  2 10 11  0  1  2 10 11  0  1  2 10 11]
 [ 3  4  5 12 13  3  4  5 12 13  3  4  5 12 13]
 [ 6  7  8 14 15  6  7  8 14 15  6  7  8 14 15]] <class 'numpy.ndarray'>
Dimension = 2
Shape = (3, 15)
Size = 45
Element data type = int64


In [ ]:
# Creating the object of ndarray using vstack()

In [28]:
a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5,])
print(a,type(a))
print("Shape =", a.shape)
print(b,type(b))
print("Shape =", b.shape)
print('-------------------------')
c=np.vstack((a,b))
print(c,type(c))
print("Dimension =", c.ndim)
print("Shape =", c.shape)
print("Size =", c.size)

[10 20 30 40 50] <class 'numpy.ndarray'>
Shape = (5,)
[1 2 3 4 5] <class 'numpy.ndarray'>
Shape = (5,)
-------------------------
[[10 20 30 40 50]
 [ 1  2  3  4  5]] <class 'numpy.ndarray'>
Dimension = 2
Shape = (2, 5)
Size = 10


In [32]:
n1=np.arange(0,9).reshape(3,3)
n2=np.arange(9,18).reshape(3,3)
print("Matrix A")
print(n1,type(n1))
print("----------------------------")
print("Matrix B")
print(n2,type(n2))

Matrix A
[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>
----------------------------
Matrix B
[[ 9 10 11]
 [12 13 14]
 [15 16 17]] <class 'numpy.ndarray'>


In [38]:
print("Hstack is =")
n3=np.hstack((n1,n2))
print(n3,type(n3))
print('------------------')
print("Dimension =", n3.ndim)
print("Shape =", n3.shape)
print("Size =", n3.size)
print("Element data type =", n3.dtype)
print('-----------------------------------')
print("Vstack is =")
n4=np.vstack((n1,n2))
print(n4,type(n4))
print('------------------')
print("Dimension =", n4.ndim)
print("Shape =", n4.shape)
print("Size =", n4.size)
print("Element data type =", n4.dtype)

Hstack is =
[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]] <class 'numpy.ndarray'>
------------------
Dimension = 2
Shape = (3, 6)
Size = 18
Element data type = int64
-----------------------------------
Vstack is =
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]] <class 'numpy.ndarray'>
------------------
Dimension = 2
Shape = (6, 3)
Size = 18
Element data type = int64
