In [ ]:
# creating an objects of using random module functions
# symtax-1: numpy.random.randint(Value)-------------> Random Integer number between 0 to value-1 

In [3]:
import numpy as np
a=np.random.randint(5) # It take 0 to n-1
print(a,type(a))
a=np.random.randint(8)
print(a,type(a))
a=np.random.randint(4)
print(a,type(a))
a=np.random.randint(10)
print(a,type(a))

4 <class 'int'>
6 <class 'int'>
3 <class 'int'>
5 <class 'int'>


In [ ]:
a = random.randint(1,3)

In [2]:
for i in range(10):
    a=np.random.randint(10)
    print(a,type(a))

8 <class 'int'>
0 <class 'int'>
6 <class 'int'>
9 <class 'int'>
5 <class 'int'>
2 <class 'int'>
8 <class 'int'>
8 <class 'int'>
2 <class 'int'>
9 <class 'int'>


In [10]:
# Generating three digit number
a=np.random.randint(100,1000)
print(a,type(a))

286 <class 'int'>
948 <class 'int'>


In [ ]:
# Syntax-2
# numpy.random.randint(Low,High)----> Random number between Low to High-1

In [14]:
for i in range(5):
    n=np.random.randint(100,1000)
    print(n,type(n))
    print('-'*10)

723 <class 'int'>
----------
373 <class 'int'>
----------
483 <class 'int'>
----------
863 <class 'int'>
----------
255 <class 'int'>
----------


In [18]:
# Generating four digit number
a=np.random.randint(1000,10000)
print(a,type(a))

8016 <class 'int'>


In [17]:
for i in range(5):
    n=np.random.randint(1000,10000)
    print(n,type(n))
    print('-'*10)

6445 <class 'int'>
----------
4651 <class 'int'>
----------
6188 <class 'int'>
----------
2398 <class 'int'>
----------
4286 <class 'int'>
----------


In [19]:
# Generating 5 digit number otp
a=np.random.randint(10000,100000)
print(a,type(a))

46386 <class 'int'>


In [29]:
for i in range(1,11):
    b=np.random.randint(10000,100000)
    print(f'otp-{i} : {b}')

otp-1 : 62654
otp-2 : 59000
otp-3 : 61527
otp-4 : 55107
otp-5 : 61658
otp-6 : 88722
otp-7 : 97108
otp-8 : 55958
otp-9 : 34478
otp-10 : 26969


In [ ]:
# Syntax-3
# numpy.random.randint(Low,High,size-- Random number between Low to High-1 with size(1-D,2-D, n-D)

In [33]:
import numpy as np
a=np.random.randint(1,10,size=2)
print(a,type(a))
print("Dimension =", a.ndim)
print("Shape =", a.shape)
print("Size =", a.size)

[1 3] <class 'numpy.ndarray'>
Dimension = 1
Shape = (2,)
Size = 2


In [36]:
a=np.random.randint(1,10,size=(3,2))
print(a,type(a))
print("Dimension =", a.ndim)
print("Shape =", a.shape)
print("Size =", a.size)

[[1 6]
 [2 2]
 [5 6]] <class 'numpy.ndarray'>
Dimension = 2
Shape = (3, 2)
Size = 6


In [37]:
a=np.random.randint(1,10,size=(2,3,4))
print(a,type(a))
print("Dimension =", a.ndim)
print("Shape =", a.shape)
print("Size =", a.size)

[[[6 2 8 1]
  [2 2 7 5]
  [7 7 6 6]]

 [[7 3 7 4]
  [8 9 6 3]
  [5 7 6 6]]] <class 'numpy.ndarray'>
Dimension = 3
Shape = (2, 3, 4)
Size = 24


In [39]:
a=np.random.randint(10,21,size=(3,4))
print(a,type(a))
print("Dimension =", a.ndim)
print("Shape =", a.shape)
print("Size =", a.size)

[[12 19 14 14]
 [10 10 15 19]
 [12 16 11 16]] <class 'numpy.ndarray'>
Dimension = 2
Shape = (3, 4)
Size = 12


In [50]:
for i in range(1,6):
    k=np.random.randint(100,200,size=(3,4))
    print(f'{i} Times: \n{k}')
    print('-'*25)

1 Times: 
[[179 101 197 160]
 [152 147 149 156]
 [130 100 124 193]]
-------------------------
2 Times: 
[[184 174 136 124]
 [192 191 194 109]
 [120 121 192 148]]
-------------------------
3 Times: 
[[144 175 181 186]
 [168 188 127 105]
 [151 152 120 127]]
-------------------------
4 Times: 
[[111 111 131 166]
 [165 111 116 141]
 [143 171 143 172]]
-------------------------
5 Times: 
[[102 166 176 173]
 [174 159 139 114]
 [153 181 140 107]]
-------------------------


In [52]:
# Here 1.2 taken as 1 and 3.4 taken 3 i.e Integer values
a=np.random.randint(1.2,3.4,size=4)
print(a,type(a))
print("Dim of a=",a.ndim)
print("Shape of a=",a.shape)


[2 1 2 1] <class 'numpy.ndarray'>
Dim of a= 1
Shape of a= (4,)


In [ ]:
# create an object of ndarray by using rand()
# Syntax-1: numpy.random.rand()--->Generating Any random floating point value between 0.0 to 1.0.

In [54]:
a=np.random.rand()
print(a,type(a))

0.7961010827109928 <class 'float'>


In [55]:
a=np.random.rand()
print(a,type(a))

0.6905122307907897 <class 'float'>


In [58]:
for i in range(10):
    n=np.random.rand()
    print(n,type(n))

0.6083014201004323 <class 'float'>
0.1472517495720017 <class 'float'>
0.4941712107678441 <class 'float'>
0.14367599731736824 <class 'float'>
0.7023393207282126 <class 'float'>
0.5967390064496778 <class 'float'>
0.8305430207166041 <class 'float'>
0.8237016690705242 <class 'float'>
0.09183161313761345 <class 'float'>
0.9472433417151548 <class 'float'>


In [63]:
for i in range(10):
    a=np.random.rand()
    print("%0.2f" %a)

0.23
0.97
0.34
0.91
0.35
0.39
0.69
0.53
0.53
0.94


In [65]:
for i in range(10):
    k=np.random.rand()
    print(round(k,2))

0.08
0.15
0.46
0.83
0.38
0.97
0.32
0.85
0.04
0.37


In [ ]:
#Syntax-2: numpy.random.rand(value)--->
#Generating Number of Random floating Values (Value times) between 0.0 to 1.0 with 1-D

In [69]:
a=np.random.rand(2)
print(a,type(a))
print("Dimension =", a.ndim)
print("Shape =", a.shape)
print("Size =", a.size)

[0.52466636 0.44832183] <class 'numpy.ndarray'>
Dimension = 1
Shape = (2,)
Size = 2


In [72]:
a=np.random.rand(10)
print(a)
print(type(a))
print("Dimension =", a.ndim)
print("Shape =", a.shape)
print("Size =", a.size)

[0.41040236 0.0812536  0.77068085 0.99404815 0.37854699 0.85160539
 0.86017617 0.94840548 0.94838579 0.64807361]
<class 'numpy.ndarray'>
Dimension = 1
Shape = (10,)
Size = 10


In [74]:
a=np.random.rand(3,4)
print(a,type(a))
print("Dimension =", a.ndim)
print("Shape =", a.shape)
print("Size =", a.size)

[[0.28277077 0.56629332 0.84116589 0.25619317]
 [0.23097835 0.39828731 0.93821735 0.62798441]
 [0.4141057  0.00453133 0.19183768 0.44071739]] <class 'numpy.ndarray'>
Dimension = 2
Shape = (3, 4)
Size = 12


In [75]:
s=np.random.rand(4,3)
print(s)
print(type(s))

[[0.00205868 0.4173691  0.46680843]
 [0.9543205  0.12248517 0.24087747]
 [0.65074378 0.36451439 0.21279593]
 [0.71675008 0.67779929 0.33970729]]
<class 'numpy.ndarray'>


In [76]:
for i in range(len(a)):
    for j in range(len(a[0])):
        print("%0.2f" %a[i,j],end=' ')
    print()

0.28 0.57 0.84 0.26 
0.23 0.40 0.94 0.63 
0.41 0.00 0.19 0.44 


In [77]:
a=np.random.rand(3,4,2)
print(a)
print(type(a))

[[[0.34882129 0.47980042]
  [0.46207968 0.87204549]
  [0.01428223 0.73560561]
  [0.44836756 0.98785663]]

 [[0.46003476 0.3765065 ]
  [0.9568863  0.65541588]
  [0.31636938 0.79491892]
  [0.25187106 0.90728244]]

 [[0.85801471 0.88818576]
  [0.00181835 0.90980883]
  [0.07362689 0.2976028 ]
  [0.78436099 0.62937572]]]
<class 'numpy.ndarray'>


In [ ]:
# Syntax-1: numpy.random.uniform()
# Generating Any random floating point value between 0.0 to 1.0.

In [78]:
import numpy as np
a=np.random.uniform()
print(a,type(a))

0.22395393511806316 <class 'float'>


In [79]:
a=np.random.uniform()
print(a,type(a))

0.38942850316572564 <class 'float'>


In [82]:
for i in range(10):
    a=np.random.uniform()
    print(a,type(a))

0.09208151130708464 <class 'float'>
0.7603166007986423 <class 'float'>
0.8421908959785463 <class 'float'>
0.1232045732682957 <class 'float'>
0.016834131299812705 <class 'float'>
0.537684521011166 <class 'float'>
0.9352938311827192 <class 'float'>
0.29570055683494245 <class 'float'>
0.951972978312742 <class 'float'>
0.08763536840623565 <class 'float'>


In [ ]:
#Syntax-2: numpy.random.unform(low,high)
#--->Generating Any random floating point value between low and high

In [83]:
a=np.random.uniform(1.2,3.5)
print(a,type(a))

1.3271964904516578 <class 'float'>


In [85]:
for i in range(10):
    k=np.random.uniform(5.3,5.7)
    print(k,type(k))

5.564218360783654 <class 'float'>
5.340956764986208 <class 'float'>
5.429945828859037 <class 'float'>
5.31317167124979 <class 'float'>
5.412123242101913 <class 'float'>
5.531372777741397 <class 'float'>
5.586841461704443 <class 'float'>
5.556291034213839 <class 'float'>
5.626732422249841 <class 'float'>
5.359954733082651 <class 'float'>


In [86]:
for i in range(1,11):
    x=np.random.uniform(1.5,1.6)
    print(x,type(x))

1.5785466284397942 <class 'float'>
1.5368929265728692 <class 'float'>
1.5218672283637324 <class 'float'>
1.5622737775802529 <class 'float'>
1.5694226144818515 <class 'float'>
1.5754992866648 <class 'float'>
1.5234146634879557 <class 'float'>
1.594940918280337 <class 'float'>
1.5957366303132408 <class 'float'>
1.5212513095600857 <class 'float'>


In [ ]:
#Syntax-3: numpy.random.uniform(low,high,size)
#--->Generating Number of Random floating Values (Row, Cols) 

In [87]:
a=np.random.uniform(1.2,1.8,size=6)
print(a)
print(type(a))

[1.32837746 1.41948187 1.79542219 1.5855555  1.21234447 1.51696419]
<class 'numpy.ndarray'>


In [88]:
b=np.random.uniform(2.3,2.8,size=(3,2))
print(b)
print(type(b))

[[2.73929387 2.63048255]
 [2.66086903 2.56465691]
 [2.47491689 2.4669648 ]]
<class 'numpy.ndarray'>


In [89]:
b=np.random.uniform(2.3,2.8,size=(2,3,2))
print(b)
print(type(b))

[[[2.54846238 2.41307683]
  [2.3502877  2.74022664]
  [2.55855129 2.56140895]]

 [[2.46862524 2.70609804]
  [2.76931882 2.56317952]
  [2.68695037 2.38484183]]]
<class 'numpy.ndarray'>


In [90]:
b=np.random.uniform(2.3,2.8,size=(4,2,3))
print(b)
print(type(b))

[[[2.46856638 2.59942927 2.77206144]
  [2.79741423 2.38600835 2.39691881]]

 [[2.39618663 2.73185944 2.4713776 ]
  [2.30389526 2.63636598 2.39514108]]

 [[2.79239852 2.33070687 2.72823258]
  [2.42465617 2.64214668 2.52455217]]

 [[2.4228836  2.51787259 2.62356045]
  [2.72018805 2.37216721 2.77732897]]]
<class 'numpy.ndarray'>
