In [ ]:
# Creating an object of ndarray using randm() method
# Syntax:- numpy.random.randn()--->Generating Any random floating point value can either +ve or -ve.

In [17]:
import numpy as np
a=np.random.randn()
print(a,type(a))

-0.2891080809151707 <class 'float'>


In [2]:
a=np.random.randn()
print(a,type(a))

-0.17650935618038263 <class 'float'>


In [6]:
for i in range(6):
    b=np.random.randn()
    print(b,type(b))

-1.117039705257782 <class 'float'>
0.012277523800302068 <class 'float'>
-0.42662587797459267 <class 'float'>
0.9742619319496056 <class 'float'>
0.3376416910244667 <class 'float'>
0.24619091455840092 <class 'float'>


In [ ]:
# Syntax-2: numpy.random.randn(value)
# Generating Number of Random floating Values (Value times) 
# for standard Normal Distribution and either +ve or -ve

In [20]:
x=np.random.randn(3)
print(x)
print(type(x))
print("Dimension =", x.ndim)
print("Shape =", x.shape)

[-2.35184471 -0.23370266 -1.53655648]
<class 'numpy.ndarray'>
Dimension = 1
Shape = (3,)


In [22]:
x=np.random.randn(10)
print(x)
print(type(x))
print("Dimension =", x.ndim)
print("Shape =", x.shape)
x.shape=(5,2)
print("Dimension =", x.ndim)
print("Shape =", x.shape)

[ 0.10889294  2.20501178  1.34798065 -1.41822077  0.55654971 -0.22292166
 -0.22365571  0.68329499 -0.81594961  0.64758645]
<class 'numpy.ndarray'>
Dimension = 1
Shape = (10,)
Dimension = 2
Shape = (5, 2)


In [12]:
for i in range(10):
    x=np.random.randn(10)
    print(x)
    print(type(x))
    print('-'*50)

[-0.72110869 -1.19253153 -0.34648689 -1.68922891  0.30693586 -0.42598644
  1.72013868  1.03797145  0.28447198  0.47230487]
<class 'numpy.ndarray'>
--------------------------------------------------
[-1.22606385 -0.94041333 -2.24451083 -0.45470873  0.52117048 -0.61317438
  0.65316627 -0.62684146 -0.08807021 -0.58773431]
<class 'numpy.ndarray'>
--------------------------------------------------
[ 0.03860716 -0.50439268  0.8898818  -0.56185213 -0.12892784 -1.41152778
 -1.10798681 -1.34378943 -0.40838784  0.46324333]
<class 'numpy.ndarray'>
--------------------------------------------------
[-0.98673417 -1.07240169  0.75189751  0.81773348  1.08542789  0.71226128
  0.58385289 -0.77488115 -0.32463459 -0.34834858]
<class 'numpy.ndarray'>
--------------------------------------------------
[ 0.05526327 -0.70960286 -1.27114227  0.19612918 -1.19139714  0.83108576
 -0.38824975  0.07459266 -0.34440336 -0.6839134 ]
<class 'numpy.ndarray'>
--------------------------------------------------
[-0.661106

In [ ]:
#Syntax-3: numpy.random.randn(Rows, Cols)--->Generating Number of Random floating Values (Row, Cols) 
#for standard Normal Distribution and either +ve or -ve with 2-D	

In [13]:
d=np.random.randn(2,3)
print(d)
print(type(d))

[[ 0.94749932  0.68304779 -1.00095086]
 [-0.26839624  0.80048949  1.84400536]]
<class 'numpy.ndarray'>


In [35]:
d=np.random.randn(4,2,3)
print(d)
print(type(d))
print('-'*40)
print("Dimension =", d.ndim)
print("Shape =", d.shape)
print("Element data type =", d.dtype)
print('-'*50)
d.shape=(24,)
print(d)
print("Dimension =", d.ndim)
print("Shape =", d.shape)
print("Element data type =", d.dtype)
print('-'*50)
d.shape=(6,4)
print(d)
print("Dimension =", d.ndim)
print("Shape =", d.shape)

[[[ 1.32430574 -0.71062083 -0.26434865]
  [-0.51968908 -0.47217751 -1.36881538]]

 [[-0.84200661  0.02473029 -1.45256658]
  [ 0.61182836  0.1931397   0.30982023]]

 [[-0.74459482 -0.21218423 -0.48499546]
  [-0.98073581  0.03575919 -0.12789737]]

 [[ 1.36563722  0.21328122  0.11324868]
  [ 0.2251134   2.0859434  -0.02286639]]]
<class 'numpy.ndarray'>
----------------------------------------
Dimension = 3
Shape = (4, 2, 3)
Element data type = float64
--------------------------------------------------
[ 1.32430574 -0.71062083 -0.26434865 -0.51968908 -0.47217751 -1.36881538
 -0.84200661  0.02473029 -1.45256658  0.61182836  0.1931397   0.30982023
 -0.74459482 -0.21218423 -0.48499546 -0.98073581  0.03575919 -0.12789737
  1.36563722  0.21328122  0.11324868  0.2251134   2.0859434  -0.02286639]
Dimension = 1
Shape = (24,)
Element data type = float64
--------------------------------------------------
[[ 1.32430574 -0.71062083 -0.26434865 -0.51968908]
 [-0.47217751 -1.36881538 -0.84200661  0.0247

In [ ]:
# create an object of ndarray by using shuffle()
# syntax-1: numpy.random.shuffle(x), here x is ndarrayobject

In [46]:
import numpy as np
a=np.arange(10)
print(a)
print("ID =", id(a))
print(type(a))
print('-'*50)
np.random.shuffle(a)
print(a)
print("ID =",id(a))
print(type(a))
print('-'*50)
np.random.shuffle(a)
print(a)
print("ID =",id(a))
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
ID = 2315405534160
<class 'numpy.ndarray'>
--------------------------------------------------
[4 1 7 5 6 3 9 2 8 0]
ID = 2315405534160
<class 'numpy.ndarray'>
--------------------------------------------------
[6 4 7 2 1 5 0 8 3 9]
ID = 2315405534160
<class 'numpy.ndarray'>


In [53]:
a=np.arange(10,110,10)
print(a,id(a),type(a))
for i in range(10):
    np.random.shuffle(a)
    print(a,id(a),type(a))

[ 10  20  30  40  50  60  70  80  90 100] 2315409830032 <class 'numpy.ndarray'>
[ 50  20  40  70  10  90  60  80  30 100] 2315409830032 <class 'numpy.ndarray'>
[ 20  30  10 100  50  70  40  60  80  90] 2315409830032 <class 'numpy.ndarray'>
[ 60  50  20  40  10  90  80  70 100  30] 2315409830032 <class 'numpy.ndarray'>
[ 40  90  50  80  10 100  60  70  30  20] 2315409830032 <class 'numpy.ndarray'>
[ 40  90  80  30  50  60  70 100  20  10] 2315409830032 <class 'numpy.ndarray'>
[ 50  80  20  30  40 100  90  10  60  70] 2315409830032 <class 'numpy.ndarray'>
[ 30  80  40  70  10  50  20  60  90 100] 2315409830032 <class 'numpy.ndarray'>
[ 50  90  60  80  30  20 100  10  40  70] 2315409830032 <class 'numpy.ndarray'>
[ 70  30  20 100  10  40  90  80  60  50] 2315409830032 <class 'numpy.ndarray'>
[ 90 100  20  80  70  10  60  30  50  40] 2315409830032 <class 'numpy.ndarray'>


In [58]:
x=np.arange(10)
print(x,id(x),type(x))
print('-'*40)
for i in range(1,11):
    np.random.shuffle(x)
    print(f'{i} Time : {x}')

[0 1 2 3 4 5 6 7 8 9] 2315405534160 <class 'numpy.ndarray'>
----------------------------------------
1 Time : [5 2 0 3 9 7 1 8 6 4]
2 Time : [6 9 8 0 2 7 5 4 3 1]
3 Time : [8 3 4 1 6 0 2 7 9 5]
4 Time : [6 3 2 7 0 9 1 5 8 4]
5 Time : [0 6 3 5 4 1 7 8 9 2]
6 Time : [7 2 9 1 5 4 6 8 3 0]
7 Time : [0 5 4 2 7 6 9 3 1 8]
8 Time : [1 7 5 8 3 0 6 2 4 9]
9 Time : [0 1 9 6 3 8 7 5 2 4]
10 Time : [9 7 8 0 5 3 2 4 6 1]


In [67]:
s="MISSISSIPPI"
print(s,type(s))
arr=np.array(list(s))
print(arr,type(arr))
print('------------------------')
for i in range(len(s)):
    np.random.shuffle(arr)
    print(f'{i+1} Time : {arr}')

MISSISSIPPI <class 'str'>
['M' 'I' 'S' 'S' 'I' 'S' 'S' 'I' 'P' 'P' 'I'] <class 'numpy.ndarray'>
------------------------
1 Time : ['S' 'I' 'S' 'I' 'I' 'P' 'I' 'S' 'P' 'M' 'S']
2 Time : ['I' 'P' 'S' 'P' 'I' 'M' 'S' 'S' 'I' 'S' 'I']
3 Time : ['S' 'M' 'P' 'I' 'P' 'S' 'I' 'S' 'I' 'I' 'S']
4 Time : ['I' 'I' 'S' 'S' 'P' 'I' 'S' 'M' 'I' 'P' 'S']
5 Time : ['M' 'S' 'I' 'P' 'I' 'I' 'S' 'S' 'S' 'P' 'I']
6 Time : ['M' 'I' 'S' 'I' 'P' 'S' 'S' 'I' 'P' 'I' 'S']
7 Time : ['I' 'S' 'S' 'M' 'I' 'I' 'P' 'P' 'S' 'S' 'I']
8 Time : ['S' 'I' 'S' 'I' 'I' 'P' 'I' 'P' 'M' 'S' 'S']
9 Time : ['I' 'I' 'S' 'P' 'I' 'S' 'S' 'I' 'P' 'S' 'M']
10 Time : ['P' 'I' 'P' 'I' 'I' 'S' 'M' 'I' 'S' 'S' 'S']
11 Time : ['I' 'I' 'S' 'P' 'I' 'S' 'P' 'S' 'S' 'I' 'M']


In [69]:
# join this letter in one string
s="MISSISSIPPI"
print(s,type(s))
arr=np.array(list(s))
print(arr,type(arr))
print('------------------------')
for i in range(len(s)):
    np.random.shuffle(arr)
    print(f'{i+1} Time : {"".join(arr)}')

MISSISSIPPI <class 'str'>
['M' 'I' 'S' 'S' 'I' 'S' 'S' 'I' 'P' 'P' 'I'] <class 'numpy.ndarray'>
------------------------
1 Time : IIPMSSISISP
2 Time : MSPISSIPIIS
3 Time : SIIIIPPSSMS
4 Time : PSSIPIISISM
5 Time : PISSPIISMIS
6 Time : PIIIMSSSPSI
7 Time : PSPSIISIIMS
8 Time : SSIISIPPIMS
9 Time : MSISSISPIIP
10 Time : SSIMPPIISIS
11 Time : SSISPIMISPI


In [78]:
# Shuffling 2-dimension data
a=np.random.randint(1,10,size=(3,4))
print(a)
print(type(a))
print('----------------------')
np.random.shuffle(a)
print(a)

[[2 8 8 8]
 [9 2 9 9]
 [9 9 5 9]]
<class 'numpy.ndarray'>
----------------------
[[2 8 8 8]
 [9 2 9 9]
 [9 9 5 9]]


In [77]:
x=np.random.randint(1,100,size=(6,5))
print(x)
print(type(x))
print('------------------------')
np.random.shuffle(x)
print(x)

[[60 62 60 90 37]
 [96 75 28 65  7]
 [35 57 90 95 59]
 [74 64 30 97  7]
 [78 65 13 98 36]
 [54 37 43  2 32]]
<class 'numpy.ndarray'>
------------------------
[[74 64 30 97  7]
 [96 75 28 65  7]
 [60 62 60 90 37]
 [54 37 43  2 32]
 [78 65 13 98 36]
 [35 57 90 95 59]]


In [84]:
# Shuffling n-dimension array
a=np.random.randint(1,100,size=(3,4,3))
print(a,type(a))
print('-----------------------')
np.random.shuffle(a)
print(a)

[[[94 93  8]
  [13 17 52]
  [63 85 99]
  [27  7 86]]

 [[67 40 95]
  [37  8 77]
  [96 28 90]
  [ 6 28 26]]

 [[12  5  2]
  [90 58 72]
  [43 67 98]
  [66 93 22]]] <class 'numpy.ndarray'>
-----------------------
[[[94 93  8]
  [13 17 52]
  [63 85 99]
  [27  7 86]]

 [[12  5  2]
  [90 58 72]
  [43 67 98]
  [66 93 22]]

 [[67 40 95]
  [37  8 77]
  [96 28 90]
  [ 6 28 26]]]


In [88]:
# Another example
a=np.arange(48).reshape(4,4,3)
print(a)
print("Dimension =", a.ndim)
print("Shape =", a.shape)
print('----------------------------')
np.random.shuffle(a)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
Dimension = 3
Shape = (4, 4, 3)
----------------------------
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [91]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr))
print('---------------------')
for i in range(len(arr)):
    np.random.shuffle(arr)
    print("Shuffle order-{} : {}".format(i+1,arr))

[1 2 3 4 5] <class 'numpy.ndarray'>
---------------------
Shuffle order-1 : [1 3 4 2 5]
Shuffle order-2 : [3 5 4 2 1]
Shuffle order-3 : [2 4 3 1 5]
Shuffle order-4 : [2 4 3 5 1]
Shuffle order-5 : [1 3 2 5 4]


In [ ]:
# Creating an object of ndarray using choice() method
# syntax:  varname=numpy.random.choice(object,size)

In [104]:
import numpy as np
x=np.arange(1,11)
print(x,type(x))
ch=np.random.choice(x)
print("Choice is {}".format(ch))
print(type(ch))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>
Choice is 6
<class 'numpy.int64'>


In [109]:
x=np.arange(2,21,2)
print(x)
print('--------------------')
for i in range(1,11):
    ch=np.random.choice(x)
    print("{} Time choice is {}".format(i,ch))

[ 2  4  6  8 10 12 14 16 18 20]
--------------------
1 Time choice is 8
2 Time choice is 6
3 Time choice is 10
4 Time choice is 4
5 Time choice is 2
6 Time choice is 14
7 Time choice is 12
8 Time choice is 10
9 Time choice is 4
10 Time choice is 18


In [119]:
# Select choice more than one
a=np.array(range(10,110,10))
print(a)
ch=np.random.choice(a,size=2)
print(ch,type(ch))

[ 10  20  30  40  50  60  70  80  90 100]
[40 50] <class 'numpy.ndarray'>


In [123]:
a=np.arange(5,51,5)
print(a)
print('-------------------------')
for i in range(10):
    ch=np.random.choice(a,size=2)
    print("{} Time choice is : {}".format(i+1,ch))

[ 5 10 15 20 25 30 35 40 45 50]
-------------------------
1 Time choice is : [45 15]
2 Time choice is : [ 5 40]
3 Time choice is : [5 5]
4 Time choice is : [45 35]
5 Time choice is : [30 50]
6 Time choice is : [ 5 35]
7 Time choice is : [20 40]
8 Time choice is : [15 50]
9 Time choice is : [15 45]
10 Time choice is : [10 25]


In [127]:
# getting 3 or more choices
a=np.arange(10,106,5)
print(a)
print('-------------------------')
for i in range(10):
    ch=np.random.choice(a,size=5)
    print("{} Time choice is : {}".format(i+1,ch))

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100 105]
-------------------------
1 Time choice is : [105  80  25  35  75]
2 Time choice is : [60 10 30 10 15]
3 Time choice is : [ 55 100  55  85  15]
4 Time choice is : [90 30 75 70 20]
5 Time choice is : [25 35 60 60 60]
6 Time choice is : [50 55 30 60 60]
7 Time choice is : [20 55 65 30 45]
8 Time choice is : [80 20 50 70 75]
9 Time choice is : [ 35  35 105 100  35]
10 Time choice is : [ 70  75  75  95 105]


In [146]:
# Getting capcha code
import numpy as np
s="ABCDEFGHJKLMNOPQRSTUVWXYZabcdefghjklmnopqrstuvwxyz123456789"
arr=np.array(list(s))
ch=np.random.choice(arr,size=5)
capcha="".join(ch)
print("Your capcha code is : {}".format(capcha))

Your capcha code is : rcWYe


In [148]:
# getting 10 random capcha codes
import numpy as np
s="ABCDEFGHJKLMNOPQRSTUVWXYZabcdefghjklmnopqrstuvwxyz123456789"
arr=np.array(list(s))
for i in range(10):
    ch=np.random.choice(arr,size=5)
    print("{} Time capcha : {}".format(i+1,"".join(ch)))

1 Time capcha : htn5u
2 Time capcha : oWWnf
3 Time capcha : xYhqU
4 Time capcha : Gyfrg
5 Time capcha : 35cTq
6 Time capcha : AeGAT
7 Time capcha : h4sgt
8 Time capcha : 6NsQl
9 Time capcha : l9JFx
10 Time capcha : 5uYek
