In [1]:
# Indexing Operation on 1-D Array
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("content of a :",a)

content of a : [10 20 30 40 50 60 70 80 90]


In [7]:
for i in range(len(a)):
    print(a[i],end=' ')

10 20 30 40 50 60 70 80 90 

In [10]:
for i in range(-1,-(len(a)+1),-1):
    print(a[i],end=' ')

90 80 70 60 50 40 30 20 10 

In [12]:
print(a[4])
print(a[-5])

50
50


In [18]:
# Indexing Operation on 2-D Array
#Syntax-1    2dArraObj[RowIndex,ColumnIndex]
                #OR
#Syntax-2    2dArraObj[RowIndex][ColumnIndex]

In [30]:
arr=np.arange(10,100,10).reshape(3,3)
print("Content of arr \n",arr)
print('----------------------')
print(arr[-3,-1])
print(arr[-2][-2])
print(arr[2][1])
print(arr[1,2],arr[-2,-1])
print(arr[0][0])

Content of arr 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
----------------------
30
50
80
60 60
10


In [33]:
# using for loop
# for i in range(3):
#     for j in range(3):
#         print(a[i][j],end=' ')
#     print()

In [36]:
#Indexing Operation on 3-D Array
# Syntax: ndarrayobject[MatrixIndex][Row Index,Col Index]
#    OR
# Syntax: ndarrayobject[MatrixIndex][Row Index][Col Index]
import numpy as np
a=np.arange(3*3*3).reshape(3,3,3)
print("content of a \n",a)

content of a 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [39]:
# Getting matrix from array
print(a[0])
print('-------------')
print(a[1])
print('-------------')
print(a[2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
-------------
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [43]:
# Getting elements from matrix
print(a[1,1,1])
print(a[2][1][2])
print(a[-3,-1,-2])
print(a[1,1,0],a[-2,-2,-3])

13
23
7
12 12


In [45]:
for i in range(len(a)):
    print(a[i])
    print('-------------')

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
-------------
[[18 19 20]
 [21 22 23]
 [24 25 26]]
-------------


In [48]:
print(a[2][0][0])
print(a[-1][-3][-3])

18
18


In [49]:
# Now using 4d matrix
import numpy as np
arr=np.arange(2*3*3*3).reshape(2,3,3,3)
print(arr)

[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]
   [24 25 26]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]]


In [70]:
# getting single matrix
print(arr[0,0])
print('-----------')
print(arr[-2][-3])
print('-----------')
print('-----------')
print(arr[1,0])
print('-----------')
print(arr[-1,-3])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-----------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-----------
-----------
[[27 28 29]
 [30 31 32]
 [33 34 35]]
-----------
[[27 28 29]
 [30 31 32]
 [33 34 35]]


In [51]:
# getting 1st cluster
print(arr[0])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
---------------
[[[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]]]


In [52]:
# getting all clusters
for i in range(2):
    print(arr[i])
    print('-------------')

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-------------
[[[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]]]
-------------


In [54]:
print(arr[1,1,1,2])

41


In [56]:
# get 46
print(arr[1][2][0][1])
print(arr[-1][-1][-3][-2])

46
46


In [57]:
print(arr)

[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]
   [24 25 26]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]]


In [59]:
# get 14
print(arr[0,1,1,2])
print(arr[-2][-2][-2][-1])

14
14
