In [5]:
# Slicing Operations 1-D Array
import numpy as np
a=np.array(range(10,100,10))
print("content of a :")
print(a)

content of a :
[10 20 30 40 50 60 70 80 90]


In [15]:
# first four numbers
print(a[0:4])
print(a[-9:-5])

[10 20 30 40]
[10 20 30 40]


In [13]:
# 70 80
print(a[6:8])
print(a[-3:-1])

[70 80]
[70 80]


In [17]:
# reverse order
print(a[::])
print('-'*20)
print(a[::-1])

[10 20 30 40 50 60 70 80 90]
--------------------
[90 80 70 60 50 40 30 20 10]


In [19]:
print(a[4:0])

[]


In [22]:
print(a[-9:-5])

[10 20 30 40]


In [23]:
print(a[::2])

[10 30 50 70 90]


In [26]:
a[1::2]

array([20, 40, 60, 80])

In [27]:
a[:]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
a[::-2]

array([90, 70, 50, 30, 10])

In [ ]:
# Slicing Operations 2-D Array

In [31]:
a=np.arange(10,100,10).reshape(3,3)
print("Content of a :")
print(a)

Content of a :
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [48]:
print(a[0:3,0:1])
print('---------------')
print(a[:,:1])
print('---------------')
print(a[-3:,-3:-2])

[[10]
 [40]
 [70]]
---------------
[[10]
 [40]
 [70]]
---------------
[[10]
 [40]
 [70]]


In [33]:
a[0:3,1:2]

array([[20],
       [50],
       [80]])

In [35]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [57]:
# 40 50 60
print(a[1:2,0:3])
print('-'*20)
print(a[-2:-1,-3:])
print('-'*20)
print(a[-2:-1,:])

[[40 50 60]]
--------------------
[[40 50 60]]
--------------------
[[40 50 60]]


In [58]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [59]:
# 10 20
# 40 50
a[0:2,0:2]

array([[10, 20],
       [40, 50]])

In [60]:
a[:2,:2]

array([[10, 20],
       [40, 50]])

In [61]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [62]:
a[-3:-1,-3:-1]

array([[10, 20],
       [40, 50]])

In [63]:
# 80 90
a[2:3,1:3]

array([[80, 90]])

In [67]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [68]:
# 40 50
# 70 80
a[1:3,0:2]

array([[40, 50],
       [70, 80]])

In [70]:
a[-2:,-3:-1]

array([[40, 50],
       [70, 80]])

In [71]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [72]:
# 20 30 
# 50 60
a[0:2,1:3]

array([[20, 30],
       [50, 60]])

In [73]:
a[-3:-1,-2:]

array([[20, 30],
       [50, 60]])

In [74]:
a[-3:-1:,-2::]

array([[20, 30],
       [50, 60]])

In [75]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [76]:
# 10 20 30
# 70 80 90
a[::2,::]

array([[10, 20, 30],
       [70, 80, 90]])

In [77]:
a[-3::2,-3::]

array([[10, 20, 30],
       [70, 80, 90]])

In [78]:
a[0:3:2,::1]

array([[10, 20, 30],
       [70, 80, 90]])

In [79]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [80]:
# 10 30
# 40 60
# 70 90
a[0:3,0:3:2]

array([[10, 30],
       [40, 60],
       [70, 90]])

In [81]:
a[:3:1,:3:2]

array([[10, 30],
       [40, 60],
       [70, 90]])

In [82]:
a[::,::2]

array([[10, 30],
       [40, 60],
       [70, 90]])

In [86]:
a[-3:,-3::2]

array([[10, 30],
       [40, 60],
       [70, 90]])

In [87]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [88]:
# Now take a courner numbers
# 10 30
# 70 90
a[0:3:2,0:3:2]

array([[10, 30],
       [70, 90]])

In [89]:
a[::2,::2]

array([[10, 30],
       [70, 90]])

In [90]:
a[-3::2,-3::2]

array([[10, 30],
       [70, 90]])

In [ ]:
# Slicing Operations n-D Array
# ndarrayobj[MatBeg:MatEnd:MatStep, RowBeg:RowEnd:RowStep, ColBeg:ColEnd:ColStep]

In [92]:
a=np.arange(3*3*3).reshape(3,3,3)
print("content of a is :")
print(a)

content of a is :
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [98]:
# 0 1
# 3 4
a[0:1,0:2,0:2]

array([[[0, 1],
        [3, 4]]])

In [102]:
a[-3:-2,-3:-1,-3:-1]

array([[[0, 1],
        [3, 4]]])

In [103]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [110]:
# 13 16
a[1:2,1:3,1:2]

array([[[13],
        [16]]])

In [113]:
a[-2:-1,-2:,-2:-1]

array([[[13],
        [16]]])

In [114]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [115]:
# 6 7 8
# 15 16 17
# 24 25 26
a[0:3,2:,0:3]

array([[[ 6,  7,  8]],

       [[15, 16, 17]],

       [[24, 25, 26]]])

In [116]:
a[:,2:,:]

array([[[ 6,  7,  8]],

       [[15, 16, 17]],

       [[24, 25, 26]]])

In [117]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [118]:
a[-3:,-1:,-3:]

array([[[ 6,  7,  8]],

       [[15, 16, 17]],

       [[24, 25, 26]]])

In [119]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [120]:
# 3 4 5
# 21 22 23
a[0:3:2,1:2:1,0:3:1]

array([[[ 3,  4,  5]],

       [[21, 22, 23]]])

In [121]:
a[:3:2,1:2,:3]

array([[[ 3,  4,  5]],

       [[21, 22, 23]]])

In [122]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [123]:
# 12 13 14
a[1:2,1:2,0:3]

array([[[12, 13, 14]]])

In [124]:
a[-2:-1,-2:-1,-3:]

array([[[12, 13, 14]]])

In [125]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [126]:
# 1 4 7
# 19 22 25
a[0:3:2,0:3,1:2]

array([[[ 1],
        [ 4],
        [ 7]],

       [[19],
        [22],
        [25]]])

In [127]:
a[:3:2,:3:1,1:2:1]

array([[[ 1],
        [ 4],
        [ 7]],

       [[19],
        [22],
        [25]]])

In [128]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [129]:
a[-3::2,-3::1,-2:-1]

array([[[ 1],
        [ 4],
        [ 7]],

       [[19],
        [22],
        [25]]])

In [130]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
# getting the corner number of each matrix
# 0 2
# 6 8
#-------
# 9 11
# 15 17
#--------
# 18 20
# 24 26

In [131]:
a[0:3,0:3:2,0:3:2]

array([[[ 0,  2],
        [ 6,  8]],

       [[ 9, 11],
        [15, 17]],

       [[18, 20],
        [24, 26]]])

In [132]:
a[:3,:3:2,:3:2]

array([[[ 0,  2],
        [ 6,  8]],

       [[ 9, 11],
        [15, 17]],

       [[18, 20],
        [24, 26]]])

In [134]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [136]:
a[-3:,-3::2,-3::2]

array([[[ 0,  2],
        [ 6,  8]],

       [[ 9, 11],
        [15, 17]],

       [[18, 20],
        [24, 26]]])